XmacsLabs/mogan

src/Data/String/analyze.cpp
src/Data/String/analyze.hpp
src/Edit/Interface/edit_repaint.cpp
tests/Data/String/analyze_test.cpp

Relate menu: `Tool -> Misc -> Show key presses`
This PR show key presses for CJK characters correctly.

Show key presses for CJK characters

---

src/Kernel/Abstractions/basic.cpp

Default to Emacs-like key bindings

---

TeXmacs/progs/texmacs/texmacs/tm-server.scm

[skip ci] default to shared buffer

---

TeXmacs/progs/doc/help-menu.scm
src/Scheme/Glue/glue_qt.cpp
src/Scheme/Scheme/glue.cpp

add show about Qt

---

src/CMakeLists.txt

sub pr of https://github.com/XmacsLabs/mogan/pull/123
with the modern CMake style, we can remove redundant code.

CMake: further simplification

---

.clang-format
src/Texmacs/Texmacs/texmacs.cpp

clang format config 
> we'd better follow the jolly style:
assignment: a= 1 but not a = 1
func apply: func () but not func()
https://github.com/XmacsLabs/mogan/pull/118#discussion_r841077011

add .clang-format

---

CMakeLists.txt

Tested via `Debug -> Misc -> Provoke C++ Error`

CMake: set CONFIG_HOST_OS

---

TeXmacs/doc/devel/xmacs/162.tm
TeXmacs/progs/graphics/graphics-utils.scm

Created a `slink` for https://github.com/XmacsLabs/mogan/raw/default/show_grid/TeXmacs/doc/devel/xmacs/162.tm in GNU TeXmacs or Mogan and then open the network tm file to view the pull request description.

[no ci] Default: show grid for the graphics tool

---

src/Plugins/Qt/qt_tm_widget.cpp

Original idea: https://www.douban.com/group/topic/43101733/?_dtcc=1&_i=06393383c6orRK

Move the mode tool bar to the left area

---

CMakeLists.txt
packages/windows/Xmacs.iss.in
packages/windows/package.sh
src/Plugins/Windows/spawn.cpp
src/Plugins/Windows/spawn.hpp

CMake: build and package for 32/64 bit on Windows

---

src/Typeset/Env/env_semantics.cpp

Another hack to fix choice

---

plugins/gnuplot/doc/gnuplot-abstract.en.tm

Fixes #237 
It costs a lot of time for us to maintain the plugins, as a result, I decided to just warn about the gnuplot version for windows user.

[no ci] Gnuplot: warning about 5.4.x, please use 5.2.x

---

.github/workflows/ci-ubuntu-18.04.yml
.github/workflows/ci-ubuntu-20.04.yml
tests/Base/base.cpp
tests/Base/base.hpp
tests/CMakeLists.txt
tests/Data/Convert/Xml/queryxml_test.cpp
tests/Data/Convert/Xml/xml_test.cpp
tests/Data/String/analyze_test.cpp
tests/Data/String/converter_test.cpp
tests/Kernel/Containers/list_test.cpp

+ qcompare for comparing TeXmacs string in a easy way
+ Add CI for Ubuntu 18.04
closes #238

Add CI for Ubuntu 18.04

---

src/Texmacs/Data/new_buffer.cpp

See comments under https://github.com/texmacs/texmacs/commit/a3eba645d1d4a283faf5775df3a71796bbc5f67f
It is a follow-up pull request of https://github.com/XmacsLabs/mogan/pull/236

Update title when saving buffer

---

TeXmacs/langs/natural/dic/english-chinese.scm

See https://gitee.com/XmacsLabs/mogan/issues/I59SWY

[no ci] Dic(zh): beamer 幻灯片

---

CMakeLists.txt
misc/CMakeLists.txt

CMake: for debian and macOS development

---

TeXmacs/packages/standard/std-math.ts
TeXmacs/progs/math/math-edit.scm

add Bmatrix support

---

plugins/code/progs/cpp-lang.scm

Add:
* nullptr
* nullptr_t
* byte
* char16_t
* char32_t
* char8_t
* int16_t
* int32_t
* int8_t
* uint16_t
* uint32_t
* uint8_t
* concept
* constexpr

Update cpp language parser-feature

---

.github/workflows/build.yaml
.github/workflows/ci-xmake-ubuntu-windows.yaml
xmake.lua

Add ci which builds mogan with xmake on ubuntu and windows

Xmake CI Support(20h)

---

CMakeLists.txt

+ Use 2 spaces for indenting
+ Put one space after `if`

CMake: indent and format

---

TeXmacs/progs/generic/generic-edit.scm
TeXmacs/progs/generic/generic-kbd.scm

Add delete word shortcut

---

src/Edit/Interface/edit_interface.cpp
src/Edit/Interface/edit_interface.hpp

Revert changes by Darcy that cause various segfaults 1h

---

.github/workflows/package-windows.yml

This pr removes unnecessary steps of ci, and fix missing c runtime library.

improve windows packager ci 5m

---

docs/devel/134.tm
src/Typeset/Table/cell.cpp
src/Typeset/Table/table.cpp
src/Typeset/Table/table.hpp

Note: the commented debug code snippets are reserved to show `How the developer was debugging`.
Convention: 134.tm describes about the bug.
Descriptions should be kept out of Github, that's why we kept the bug desc in 134.tm.

[134] Table: Fix the width of the joined cell 10h

---

docs/devel/112.tm
src/System/Language/text_language.cpp
tests/Data/String/converter_test.cpp

Implemented the basic rule of https://www.w3.org/International/clreq/#prohibition_rules_for_line_start_end
It may break other rules.

[112] Chinese: Prohibition Rules for Line Start and Line End 4h30m

---

.github/workflows/package-debian.yml

* Before adding new features and new modules, please go to issues to submit the relevant feature description first.
* Write good commit messages and use the same coding conventions as the rest of the project.
* Please commit code to dev branch and we will merge into master branch in feature
* Ensure your edited codes with four spaces instead of TAB.
------
* 增加新特性和新模块之前，请先到issues提交相关特性说明，经过讨论评估确认后，再进行相应的代码提交，避免做无用工作。
* 编写友好可读的提交信息，并使用与工程代码相同的代码规范，代码请用4个空格字符代替tab缩进。
* 请提交代码到dev分支，如果通过，我们会在特定时间合并到master分支上。
* 为了规范化提交日志的格式，commit消息，不要用中文，请用英文描述。

fix cache collision

---

.github/workflows/ci-xmake-windows.yml

this ci adjusts mingw installation and xmake caching, to accelerate build

[3_16] xmake: github action for building using msys2 on Windows

---

tests/Kernel/Types/tree_test.cpp

[14_1] add tests for tree.cpp

---

xmake.lua

rc was introduced from separate target, and it will be enabled only under windows environment.

[8_1] add icon for mogan under windows

---

devel/23_15.tm

Related Issue: https://github.com/XmacsLabs/mogan/issues/185

[23_15] Task: a new way to change the default alignment setting

---

devel/23_14.tm

[23_14] Task: Change mouse style when entering the mode of moving

---

docs/.vitepress/config.ts

[5_12] Enable search for the website

---

TeXmacs/progs/graphics/graphics-menu.scm

[23_12] Move Exit Graphics Button to right

---

devel/52_1.tm

This is the document about the fix: [52_1] Fix the width of the joined cell.

[52_1] doc: Fix the width of the joined cell

---

src/Typeset/Table/cell.cpp
src/Typeset/Table/table.cpp
src/Typeset/Table/table.hpp

Migrate bug fixes for relevant table width from version 1.1.

[52_1] Table: Fix the width of the joined cell

---

.github/PULL_REQUEST_TEMPLATE.md

[54_2] Chore: Pull Request template

---

TeXmacs/progs/graphics/graphics-env.scm
TeXmacs/progs/graphics/graphics-main.scm
devel/23.tm

In the past PR #815 , we add a feature that the cursor style will change in MOVE MODE. Now, this feature is usable in ROTATE and ZOOM MODE too.

[23_28] Change Cursor Style when Rotate or Zoom

---

devel/23.tm

[23_28] Doc: Change Cursor Style when Rotate or Zoom

---

bin/format
docs/guide/Contribution.md
docs/zh/guide/Contribution.md

Add documentation for bin/format. And add support for archlinux.

[16_5] Add documentation and support for archlinux to `bin/format`

---

.github/workflows/ci-xmake-wasm.yml
bin/config_wasm

To fix the broken wasm CI.
Use elvish to set the emsdk path explicitly

[32_8] xmake: fix for wasm

---

devel/23.tm

Doc: Draw arc by center. See #1038

[23_27] Doc: Draw arc by center

---

.github/workflows/ci-xmake-windows.yml

Add github action to build and test on plat windows.
plat windows means build using msvc in xmake.

[37_1] Github Action on plat windows to build and test

---

TeXmacs/progs/doc/tmweb.scm
TeXmacs/tests/24_4-tm-src/24-title.tm
TeXmacs/tests/24_4.scm

Close https://github.com/XmacsLabs/mogan/issues/1046
I don't know why there is a problem with the system_wait function, I think we should cover it with tests in lolly first.
Here I will comment it temporarily.
cc: #1047

[24_4] Fix: tmweb-convert-file-dir bug & Support Integration test

---

devel/18.tm
devel/49.tm
devel/release_1.2.0.tm

[49] add new tasks

---

tests/Plugins/Database/database_basic_function_test.cpp

fix the query modified in db unitest.

[55_2] fix query modified in database test

---

TeXmacs/progs/init-code.scm
src/Mogan/Code/code.cpp
src/Mogan/app_type.hpp
src/Texmacs/Server/tm_server.cpp
xmake.lua

Mogan Code on wasm
+ [x] xmake target code on wasm only
+ [x] app type CODE
+ [x] scheme entry: init-code.scm

[48_2] Mogan Code on wasm

---

src/Plugins/Qt/qt_menu.cpp

Port #405  to branch-1.2.
Fix right click on wasm.

WASM: fix right click freeze issue

---

devel/24.tm
devel/24_5.tm

[24] add doc for tm2html tool

---

src/Mogan/Draw/draw.cpp
xmake.lua

[50_1] Wasm for mogan draw init config

---

misc/xmake/packages.lua

[53_12] fix use lolly 1.2.7

---

src/System/config.h.xmake
xmake.lua

Remove obsolete tests and configvars

[49_4] remove useless checks

---

docs/guide/ChangeLog_v1.1.5.md

Fix a typo in changelog v1.1.5

[1.1.5] Fix typo

---

README.md
README_ZH.md

Re-branding Mogan as a STEM suite in README.
+ EN: https://github.com/XmacsLabs/mogan/blob/da/62_1/stem_suite/README.md
+ ZH: https://github.com/XmacsLabs/mogan/blob/da/62_1/stem_suite/README_ZH.md

[62_1] Update README for Mogan STEM Suite

---

devel/63.tm
devel/63_1.tm
devel/64.tm
devel/64_1.tm
devel/release_1.2.0.tm

[63][64] add tasks to port bugfix from upstream

---

devel/29.tm

Refactor the relevant code of project 29 to improve code readability and neatness

[29] Task: Refactor relevant code to improve code quality

---

docs/guide/Develop_on_macOS.md
docs/zh/guide/Develop_on_macOS.md

[5_14] Warn about xmake 2.8.3 on macOS

---

devel/18.tm
devel/18_1.tm

Embedded document is removed in #1178, thus all incoming changes should be submit to texmacs.

[18] change document to match recent changes

---

.github/workflows/ci-xmake-macos.yml
.github/workflows/ci-xmake-ubuntu.yml

separate xrepo packages on macOS/ubuntu

[58_4] separate xrepo packages on macOS

---

.github/workflows/ci-xmake-macos.yml
.github/workflows/ci-xmake-ubuntu.yml

separate xrepo packages on ubuntu

[58_5] separate xrepo packages on ubuntu

---

TeXmacs/progs/graphics/graphics-drd.scm

Fix the bug that prevent inner color operation in ellipse, arc and circle

[23_1] Fix ellipse, arc, circle inner color

---

.github/workflows/ci-xmake-archlinux.yml

Add xmake build CI for archlinux.

[58_7] Add CI for archlinux

---

docs/guide/Develop_on_Linux.md

Add instructions for fedora in the development documentation
Complete installation in docker and note down the required commands

[5_15] Update Develop_on_Linux.md for Fedora

---

src/Edit/Interface/edit_interface.cpp
src/Edit/Interface/edit_interface.hpp
src/Edit/Interface/edit_mouse.cpp
src/Edit/Interface/mouse_cursor_style.cpp
src/Edit/Interface/mouse_cursor_style.hpp
src/Graphics/Gui/message.hpp
src/Graphics/Gui/widget.cpp
src/Plugins/Qt/qt_simple_widget.cpp

Remove Qt-related code and abstract the cursor-style code.

[23_14] New Design of Cursor Style class

---

devel/63.tm
devel/63_2.tm

[63] add task of merge indice of citations

---

TeXmacs/packages/standard/std-automatic.ts

Port patch of toc from upstream, fix abnormal indentation in toc
see title

[63_1] definition of toc-5 seems wrong

---

TeXmacs/plugins/html/progs/convert/html/tmhtml-expand.scm
TeXmacs/plugins/html/progs/convert/html/tmhtml.scm

[24_6] fix underline missing bug

---

xmake/packages.lua

This reverts commit c429159c316b7fd21628166c15dfa5a33f299f4c.

[41_6] Revert: Add require ghostscript 10.02.0

---

xmake/draw.lua

reduce the size of draw_wasm by remove plugins

[50_3] reduce the size of draw.data by remove plugins

---

xmake/draw.lua

[50_3] reduce the size of draw.data by remove plugins part 2

---

xmake/draw.lua

This reverts commit 499c575559cf4f26305f98a59b67ea56b79cda5e.

[48_11] Revert: -sASYNCIFY for Mogan Draw on wasm

---

xmake/research.lua

[37_7] slim installer by removing opengl

---

docs/.vitepress/config.ts

修正了中文文档的链接, 差点以为墨干的中文文档除了第一页其余都是英文 😂

[5_16] * docs/.vitepress/config.ts: fixed a link

---

devel/release_1.2.1.tm

[1.2.1] add more discarded revisions

---

src/Typeset/Concat/concat_post.cpp

[74_1] fix underline extending bug

---

devel/74_2.tm
devel/release_1.2.1.tm

Update project 74 and corresponding commits.

[74] update documents

---

src/Typeset/Page/new_breaker.cpp

[74_2] fix crash when breaking page in large table

---

TeXmacs/tests/74_2.scm
TeXmacs/tests/tm/74_2.tm

[74_2] add automated integrated test

---

TeXmacs/tests/tm/74_1.tm

This test is hard to be execute automatically, thus provide a test document

[74_1] add integrated test for 74_1

---

devel/7.tm
devel/7_9.tm
devel/release_1.2.1.tm

update information of several texmacs revisions

[1.2.1] update information of several texmacs revisions

---

TeXmacs/progs/language/std-symbols.scm

[7_9] Fix bug: Certain semantic selections crash the editor

---

devel/11.tm
devel/release_1.2.1.tm

[11] update migration status of several revision

---

packages/windows/packages/app.mogan/meta/package.in.xml
packages/windows/packages/app.shortcut/meta/package.in.xml
xmake.lua

Allow user to choose whether register the file association

[73_4] add choice box to allow disabling file association selection

---

TeXmacs/packages/customize/language/chinese.ts

Improve rendering of doc-data macro, to fit user habits of Chinese document.

[69_10] improve doc-data in chinese document

---

.github/workflows/ci-macos-arm64.yml
.github/workflows/ci-xmake-macos.yml

[73_5] Tune yaml for macOS ci

---

.github/workflows/cd_research_on_ubuntu_22_04.yml
.github/workflows/ci-xmake-ubuntu.yml
xmake-requires.lock
xmake/packages.lua

1. Upgrade lolly to 1.3.17
2. Downgrade cpr to 1.8.3
3. Use system libcurl

[73_3] tune libcurl on UOS

---

docs/guide/Install.md
docs/zh/guide/Install.md

+ https://github.com/XmacsLabs/mogan/blob/da/1.2.3/install/docs/guide/Install.md
+ https://github.com/XmacsLabs/mogan/blob/da/1.2.3/install/docs/zh/guide/Install.md

[1.2.3] Installation

---

.github/workflows/cd_research_on_ubuntu_20_04.yml
.github/workflows/ci-xmake-ubuntu-focal.yml
.github/workflows/ci-xmake-ubuntu-jammy.yml

+ Use Qt 5 on Ubuntu 20.04
+ Use Qt 6 on Ubuntu 22.04

[73_23] Add CI for Ubuntu 20.04

---

TeXmacs/packages/customize/language/chinese.ts
TeXmacs/tests/tm/69_11.tm
src/Typeset/Env/env_exec.cpp

1. Support hanzi for the number primitive
2. 部分I 改为 第I部分

[69_11] Support hanzi for the number primitive

---

src/System/config.h.xmake
xmake.lua

Clean up code, and accelerate build.

 [78_6] remove unnecessary cpp check

---

src/Mogan/Code/code.cpp
xmake.lua
xmake/code.lua

[70_5] xmake: enable Mogan Code on windows

---

TeXmacs/progs/language/minimal-test.scm

[70_6] add test for packrat

---

TeXmacs/plugins/binary/progs/binary/aspell.scm
TeXmacs/plugins/binary/progs/binary/hunspell.scm
TeXmacs/tests/tm/33_2.tm
src/Plugins/Ispell/ispell.cpp

+ hunspell binary plugins
+ aspell binary plugins
Unify the way to find the spell checker.
Open `TeXmacs/tests/tm/33_2.tm`, and click `Edit->Spell`
Note: hunspell is not available on windows in this pull request

[33_2] Binary plugins for aspell and hunspell

---

src/Data/Tree/tree_cursor.cpp

Reduce build warnings.
No need.

[78_3] Fix non-void function does not return a value in all control paths in tree_cursor

---

xmake/research.lua

Rework on xpack packaging for windows.
Continued pr for the research xmake script rework (https://github.com/XmacsLabs/mogan/pull/1699).
Tested on Windows, no need to test on Linux and macOS.
Follow steps in `.github/workflows/cd_research_on_windows.yml`

[73_29] xmake: fix xpack on windows

---

TeXmacs/plugins/binary/progs/binary/conda.scm
TeXmacs/tests/tm/61_2.tm

+ find-binary-conda
+ version-binary-conda (does not work on Windows)
+ conda-env-python-list
for the python and python-implemented plugins
+ [x] Linux
+ [x] macOS
+ [x] Windows
Open `TeXmacs/tests/tm/61_2.tm`

[61_2] Binary: conda binary plugin

---

TeXmacs/plugins/physics/LICENSE
TeXmacs/plugins/physics/README.md
TeXmacs/plugins/physics/doc/physics.en.tm
TeXmacs/plugins/physics/packages/contrib/physics.ts
TeXmacs/plugins/physics/progs/contrib/physics/physics-drd.scm

as title
Make the physics plugin as the built-in plugin
Open `Help->Plugin->Physics`

[61_4] Style: physics v1.0.0

---

TeXmacs/plugins/binary/progs/binary/gnuplot.scm
TeXmacs/tests/tm/61_5.tm

as title
Part 1 of gnuplot plugin rework
+ [x] macOS
+ [ ] Linux
+ [x] Windows
Open `61_5.tm`

[61_5] Binary: gnuplot binary plugin

---

TeXmacs/plugins/data/progs/data/scheme.scm
TeXmacs/plugins/data/progs/init-data.scm
TeXmacs/progs/init-beamer.scm
TeXmacs/progs/init-code.scm
TeXmacs/progs/init-draw.scm
TeXmacs/progs/init-research.scm

Move scheme format definition to data plugins.
Unify code data format to data plugins
Open any scheme file to test it.

[70_7] Data: scheme data plugin

---

TeXmacs/plugins/data/progs/data/image.scm
TeXmacs/plugins/data/progs/init-data.scm
TeXmacs/progs/convert/images/image-format.scm
TeXmacs/progs/init-beamer.scm
TeXmacs/progs/init-code.scm
TeXmacs/progs/init-draw.scm
TeXmacs/progs/init-research.scm

Code refactoring
Open `TeXmacs/tests/tm/38_*.tm`

[38_9] Data: image format as part of the data plugins

---

docs/guide/OSPP_2024_Tab.md

OSPP 2024 Project document on website

[5_23] OSPP 2024 Project: Add multi-tab display and switch functions

---

TeXmacs/progs/lolly/data-test.scm

Added test cases for lolly::data
xmake r data-set

[14_8] Added test cases for lolly::data

---

tests/L3/Graphics/Types/equations_test.cpp

Added test cases for Graphics-Types-equations.cpp
```
xmake build equations_test
xmake r equations_test
```

[14_10] Added test cases for src/Graphics/Types/equations.cpp

---

.github/workflows/ci-xmake-windows.yml
src/Data/Parser/preprocessor_parser.cpp
xmake.lua
xmake/packages/l/lolly/xmake.lua
xmake/vars.lua

+ Upgrade to lolly 1.4.22
+ Use ranged for loop on array<string>
Ranged for loop is better than index based for loop.
Test if the `#` leading comment works fine in Scheme/Python code block.

[75_26] Upgrade to lolly 1.4.22 and use ranged for loop on array<string>

---

TeXmacs/progs/part/part-shared.scm

as title
Do not know how to reproduce it in a minimal and reproducible doc. And the code changed is obviously wrong before.
Tested on my personal doc in book style.

[29_10] Fix PDF export of parted doc in book style

---

tests/Data/Parser/string_parser_test.cpp

Added test cases for src/Data/Parser/string_parser.cpp
The current string_parser can handle most strings, but it cannot handle the **'** or **"** in the string
```
xmake build string_parser_test
xmake r string_parser_test
```

[14_12] Added test cases for src/Data/Parser/string_parser.cpp

---

README.md

[54_3] Add discord

---

src/Data/Convert/Mogan/to_tmu.cpp

* use `binary_to_hexadecimal` to optimize performance when saving large images.
* remove line truncate mechanism of tmu format
`binary_to_hexadecimal` is obviously faster. Threshold of line truncator is set to 65535, so that ordinary document will not trigger truncating in tmu, thus remove it can make code clean and improve performance.
As same as other pr about tmu.

[66_8] remove useless code in to_tmu

---

src/Data/Convert/Mogan/to_tmu.cpp

as title
Any changes to from_tmu/to_tmu will trigger a bump of the tmu version
no need.

[66_8] TMU: bump tmu version to 1.0.2

---

TeXmacs/plugins/pandoc/progs/binary/pandoc-binary.scm

Pandoc Binary plugin
Locating the position of executable files and determining whether they exist.
(catch 'error
(lambda ()
(display "Loading module…\n")
(load "./TeXmacs/plugins/pandoc/pandoc-binary.scm")
(display "Module loaded. Testing function…\n")
(find-binary-pandoc))
(lambda (err)
(display "Error during module load or function call: ")
(display err)
(newline)))

[24_8] Add Pandoc Binary plugin

---

TeXmacs/plugins/s7/srfi/srfi-78.scm
TeXmacs/progs/kernel/boot/boot-s7.scm
TeXmacs/progs/kernel/logic/logic-test.scm
xmake.lua

+ Add `define-library`, `import` in boot.scm
+ Enable `logic-test.scm`
+ Add tests under TeXmacs/progs/kernel to scheme tests
+ `(exit -1)` when there are failures
First attempt of the check test frame.
CI

[61_8] Add scheme test on kernel/logic

---

TeXmacs/plugins/s7/srfi/srfi-78.scm
TeXmacs/tests/43_2.scm

Use SRFI-78 check to simplify test
Better test framework
```
xmake r 43_2
```

[43_2] Use SRFI-78 check to test

---

TeXmacs/plugins/s7/s7/scheme/base.scm
TeXmacs/plugins/s7/s7/scheme/file.scm
TeXmacs/plugins/s7/s7/srfi/srfi-1.scm
TeXmacs/plugins/s7/s7/srfi/srfi-13.scm
TeXmacs/plugins/s7/s7/srfi/srfi-78.scm

+ Add SRFI 13
+ Add r7rs base and file
+ Update SRFI 1 and 78

[61_7] S7: update scheme lib

---

xmake/packages/l/lolly/xmake.lua
xmake/vars.lua

Key change of this upgrade: https://github.com/XmacsLabs/lolly/commit/3e42c627a93efd4515b83bc4d3bd536e19272d3e

[75_32] Upgrade to lolly 1.4.27

---

TeXmacs/plugins/guile/guile/texmacs/protocol.scm
TeXmacs/plugins/guile/guile/tm-guile.scm
TeXmacs/plugins/guile/progs/binary/guile.scm
TeXmacs/plugins/guile/progs/init-guile.scm

The first pull request of the GNU Guile plugin. Just display the welcome message.
Make Mogan the best software to learn scheme.
Just `Insert -> Session -> GNU Guile` on macOS or GNU/Linux.

[61_12] Guile: display the welcome message

---

TeXmacs/plugins/chez/packages/code/chez.ts
TeXmacs/plugins/chez/progs/code/chez-edit.scm
TeXmacs/plugins/goldfish/packages/code/goldfish.ts
TeXmacs/plugins/goldfish/progs/code/goldfish-edit.scm
TeXmacs/plugins/goldfish/progs/init-goldfish.scm
TeXmacs/plugins/guile/packages/code/guile.ts
TeXmacs/plugins/guile/progs/code/guile-edit.scm
TeXmacs/plugins/r7rs/packages/code/r7rs.ts
TeXmacs/plugins/r7rs/progs/code/r7rs-edit.scm
TeXmacs/plugins/r7rs/progs/code/r7rs-lang.scm
TeXmacs/plugins/r7rs/progs/data/r7rs.scm

+ Code/Data plugins for R7RS
+ Chez: use R7RS code plugin for syntax
+ Guile: use R7RS code plugin for syntax
+ Goldfish: use R7RS code plugin for syntax
Enable syntax highlight for Guile and Chez.
+ Insert -> Session -> Chez
+ Insert -> Session -> Guile
+ Insert -> Session -> Goldfish

[61_15] R7RS: code/data plugins for Scheme defined in R7RS

---

TeXmacs/progs/lolly/general-url-test.scm
TeXmacs/progs/lolly/generalURL-test.scm

as title
Test suite for URL operations
xmake r generalURL-test

[14_14] Add general-url-test

---

TeXmacs/progs/lolly/general-url-test.scm

Modified `regtest-url-complete`  and added some notes for later study

[14_14] refine general-url-test

---

TeXmacs/progs/texmacs/menus/file-menu.scm
TeXmacs/progs/texmacs/texmacs/tm-files.scm

This reverts commit 168ec56f91bcc2596e9e0dfbaedf42b097bd6b6c.

[66_9] Revert TMU: switch to tmu for Save and Save as

---

TeXmacs/plugins/binary/progs/binary/pandoc.scm
docs/guide/plugin_binary_pandoc.md
docs/zh/guide/plugin_binary_pandoc.md

Add Pandoc binary document and move pandoc.scm to right place.

[24_13] Pandoc-binary doc

---

TeXmacs/progs/config/preference-test.scm

Add unit test for `preferences.hpp`.
`xmake r preference-test`.

[14_15] Add unit test for preference

---

.github/workflows/ci-xmake-archlinux.yml
.github/workflows/ci-xmake-debian-bookworm.yml
.github/workflows/ci-xmake-macos.yml
.github/workflows/ci-xmake-ubuntu-jammy.yml
.github/workflows/ci-xmake-ubuntu-noble.yml
.github/workflows/ci-xmake-windows.yml
TeXmacs/plugins/docx/progs/data/docx.scm
TeXmacs/tests/24_15.scm
TeXmacs/tests/tm/24_15.tm

Added converter for tm, tmu to docx.
`xmake r 24_15`

[24_15] Add docx converter & test

---

src/Plugins/Qt/QTMTabPage.cpp
src/Plugins/Qt/QTMTabPage.hpp

See in [here](https://github.com/XmacsLabs/mogan/pull/1986)

[81_6] Quickly hide the active tab after closing

---

TeXmacs/plugins/goldfish/goldfish/liii/os.scm
TeXmacs/plugins/goldfish/goldfish/liii/uuid.scm
TeXmacs/plugins/goldfish/goldfish/scheme/boot.scm
TeXmacs/plugins/goldfish/goldfish/scheme/process-context.scm
TeXmacs/plugins/goldfish/src/goldfish.cpp
TeXmacs/plugins/goldfish/src/goldfish.hpp
xmake/goldfish.lua
xmake/packages.lua
xmake/packages/s/s7/port/xmake.lua
xmake/research.lua
xmake/vars.lua

[61_7] Goldfish: bump 17.10.1 rc1

---

TeXmacs/plugins/goldfish/goldfish/liii/os.scm
TeXmacs/plugins/goldfish/goldfish/liii/sys.scm
TeXmacs/plugins/goldfish/src/goldfish.cpp
TeXmacs/plugins/goldfish/src/goldfish.hpp

[61_7] bump to Goldfish 17.10.1 rc2

---

src/Plugins/Qt/qt_tm_widget.cpp

Fix the display issue of the tab bar on MacOS
To fix this:
Please conduct tests @Oyyko .
And `use_unified_toolbar` should be a preference, you should test both `on` and `off` scenarios

[81_7] Fix the display issue of the tab bar on MacOS

---

TeXmacs/progs/texmacs/texmacs/tm-files.scm
TeXmacs/tests/tmu/66_10.tmu

as the title
Migrate XmacsLabs/planet to tmu format
see 66_10.tmu

[66_10] TMU: open external TMU in Mogan

---

TeXmacs/tests/tmu/66_11.tmu
src/Data/Convert/Mogan/to_tmu.cpp

as the title
to make the pr files happy
see 66_11.tmu on github pull requests

[66_11] TMU: append a newline character to the end of the TMU doc

---

TeXmacs/plugins/goldfish/goldfish/goldfish/repl.scm

[61_7] Goldfish: fix error handling for error without message

---

xmake/research.lua

[73_22] xmake: ends with portable.zip for portable MoganResearch

---

src/Data/Tree/tree_analyze.cpp
src/Edit/Modify/edit_delete.cpp
src/System/Language/impl_language.hpp
src/System/Language/language.cpp
src/System/Language/language.hpp
src/System/Language/math_language.cpp
src/System/Language/prog_language.cpp
src/System/Language/scheme_language.cpp
src/System/Language/text_language.cpp
src/System/Language/verb_language.cpp
src/Typeset/Concat/concat_macro.cpp
src/Typeset/Concat/concat_text.cpp
src/Typeset/Concat/concater.cpp

as the title
For syntax highlighting in multiple paragraphs.
Observe the ip,tree,parent_ip, parent_tree when:
1. Open a tmu doc with code blocks
2. Delete the characters in the code blocks
3. Edit -> Copy -> Copy to image

[70_12] Language: add ip for advance

---

xmake.lua

@UnbSky reports that this lock crash xmake and fails to compile

[1.2.9] xmake: unlock requires

---

src/Texmacs/Server/tm_server.cpp
xmake/vars.lua

as the title
The functions in goldfish is useful and could be adopted to solve problems.

[61_7] Enable Goldfish glues for the TeXmacs scheme interpreter

---

TeXmacs/plugins/docx/progs/data/docx.scm
TeXmacs/progs/init-research.scm

Add docx export option in the GUI toolbar and improve the docx export process.
Choose a TeXmacs file and export it by "File->Export->docx..."
Here is a tm file:
Then here is exported docx file:

[24_17] HTML: docx data plugin

---

docs/guide/plugin_data_docx.md
docs/zh/guide/plugin_data_docx.md

Add two documents for data_docx

[24_18] Add documents for data_docx

---

TeXmacs/plugins/docx/progs/data/docx.scm

Fix the problem of missing titles and images when exporting to docx.
In previous versions, exporting `tm`, `tmu` files to `docx` format would be missing titles and images. The main causes are as follows:
1. Missing title: The problem arises because string-save saves the output of `serialize-html` function, which only converts `html-stree` to `html-snippet` and is not the final output of exporting to html. Change it to `export-buffer-main` to include the export to html process completely;
2. Missing pictures: the missing pictures are mainly due to the fact that when executing the pandoc command, the execution environment is not consistent with the path of exporting to html, so the picture information can not be obtained, which has been fixed now.
tm：
html:
docx:

[24_20] Fix the problem of missing titles and images when exporting to docx

---

TeXmacs/plugins/code/progs/code/default-ast-lang.scm
src/System/Language/ast_language.cpp

Fix rainbow brackets
Wrong rainbow brackets description and highlight

[70_15] Fix rainbow brackets

---

TeXmacs/progs/generic/format-geometry-edit.scm

+ C-M-up to make the image bigger vertically
+ C-M-down to make the image smaller vertically

[59_33] Adjust shortcuts to resize the image vertically

---

.gitignore
src/Graphics/Fonts/font_database.cpp

On some big doc:
6467 ms -> 5223 ms
3465 ms -> 3027 ms
font_database_styles is computing every time, very slow

[11_35] Performance tuning on font_database_styles

---

TeXmacs/plugins/goldfish/goldfish/liii/hash-table.scm
TeXmacs/plugins/goldfish/goldfish/srfi/srfi-125.scm
TeXmacs/plugins/literate/progs/utils/literate/lp-build.scm
TeXmacs/plugins/literate/progs/utils/literate/lp-edit.scm
src/Graphics/Fonts/smart_font.cpp
src/Scheme/Glue/glue_basic.lua

+ as title For performance improvement
+ Show the benchmark info of build-buffer

[79_5] Literate: dump the code only when there are modifications

---

src/Plugins/Treesitter/lang_parser.cpp

Fix some root node cannot find

[70_17] Fix some root node cannot find

---

docs/guide/plugin_binary_pandoc.md
docs/guide/plugin_data_docx.md
docs/zh/guide/plugin_binary_pandoc.md
docs/zh/guide/plugin_data_docx.md

As title
To help user have a better understanding about how to use those function

[24_24] Refine pandoc binary and docx data plugin doc

---

TeXmacs/plugins/html/progs/convert/data/css.scm
TeXmacs/plugins/html/progs/convert/data/sxhtml.scm
TeXmacs/plugins/html/progs/convert/data/sxml.scm
TeXmacs/plugins/html/progs/convert/data/xmltm.scm
TeXmacs/plugins/html/progs/convert/html/htmltm.scm
TeXmacs/plugins/html/progs/convert/html/tmhtml.scm
TeXmacs/plugins/html/progs/convert/mathml/mathtm.scm

as title
And we migrated more code to the html plugin

[24_25] HTML: upgrade to 20240924

---

TeXmacs/doc/main/Mogan.en.tmu
TeXmacs/doc/main/Mogan.zh.tmu

Solve the wrong reference link in Chapter 3.8

[39_13] update doc in Chap. 3.8

---

.github/workflows/cd_research_on_debian_bookworm.yml
packages/debian/package.sh
xmake/vars.lua

[1.2.9.6] bump to 1.2.9.6

---

CONTRIBUTING.md
CONTRIBUTING_ZH.md
README.md
README_ZH.md
docs/guide/Test.md
docs/zh/guide/Test.md

1. Updated the test guide, add a new command to do all intergration tests.
2. Updated the README and CONTRIBUTING, add a Chinese version of CONTRIBUTING.

[5_15] Update developers' guide for v1.2.9.x

---

src/Graphics/Fonts/smart_font.cpp
src/Plugins/Freetype/unicode_font.cpp

```
<image|<tuple|<#255044462D312E340A25ACDC20ABBA0A312030206F626A0A3C3C202F54797065202F436174616C6F67202F5061676573203220302052203E3E0A656E646F626A0A382030206F626A0A3C3C202F466F6E74203320302052202F584F626A656374203720302052202F457874475374617465203420302052202F5061747465726E2035203020520A2F53686164696E67203620302052202F50726F63536574205B202F504446202F54657874202F496D61676542202F496D61676543202F496D61676549205D203E3E0A656E646F626A0A31312030206F626A0A3C3C202F54797065202F50616765202F506172656E74203220302052202F5265736F75726365732038203020520A2F4D65646961426F78205B20302030203435322E33303636373839393431203333372E393931383735205D202F436F6E74656E7473203920302052202F416E6E6F7473203130203020520A3E3E0A656E646F626A0A392030206F626A0A3C3C202F4C656E67746820313220302052202F46696C746572202F466C6174654465 …
```

[7_14] Fix crash when pasting the source code of image

---

xmake/research.lua

find_bracket_sub in src/Edit/Interface/edit_cursor.cpp needs to be improved later

[7_16] Set stack size on Windows to 16M to avoid stack overflow

---

TeXmacs/plugins/julia/progs/code/julia-lang.scm

[61_17] Julia: fix Apostrophe greys out code

---

.github/workflows/ci-xmake-fedora.yml
xmake/packages.lua
xmake/packages/m/mimalloc/xmake.lua

+ Add CI for Fedora
+ Tune deps:
- Use libcurl installed by dnf
- Use libpng installed by dnf
- Use mimalloc installed by dnf

[73_36] Add CI for Fedora 41

---

TeXmacs/plugins/goldfish/doc/goldfish.en.tm
TeXmacs/plugins/goldfish/doc/goldfish.zh.tm
TeXmacs/plugins/goldfish/goldfish/goldfish/repl.scm
TeXmacs/plugins/goldfish/goldfish/texmacs/protocol.scm
TeXmacs/plugins/goldfish/progs/init-goldfish.scm

[61_7] Goldfish: encoding fix

---

docs/.vitepress/config.ts

added tutorial on Mogan to website

[5_35] updated topbar of the website

---

docs/guide/FAQ.md
docs/guide/Mogan_versus_TeXmacs.md

Hello, sorry, I was in the wrong repo.
Changed "v.s." to "vs.". Also corrected some grammar in "Mogan_versus_TeXmacs.md" for clarity.
As discussed on [https://github.com/XmacsLabs/mogan.app/pull/2](https://github.com/XmacsLabs/mogan.app/pull/2).
Since only some text was changed, it should not create any conflicts.
Thanks in advance.

[5_19] Fix a minor typo and some grammar

---

.github/workflows/ci-macos-arm64.yml
.github/workflows/ci-xmake-macos.yml
.github/workflows/ci-xmake-windows.yml

bump action/cache version to v4
v2 is outdated

[73_38] bump action/cache version to v4
