XmacsLabs/mogan

- TeXmacs/progs/kernel/texmacs/tm-define-test.scm
- TeXmacs/progs/kernel/texmacs/tm-define.scm
> [skip ci] S7: procedure-symbol-name on anonymous procedure

- src/Texmacs/Texmacs/texmacs.cpp
Fix https://savannah.gnu.org/bugs/?61659 by Philippe Joyez
> [no ci] backport: fix 61659

- .github/workflows/ci-linux.yml
- .github/workflows/ci-macos.yml
- CMakeLists.txt
- src/Plugins/Curl/curl.cpp
- src/Plugins/Curl/curl.hpp
- src/System/Files/web_files.cpp
Launch mogan via terminal, check on `Debug -> io`.
And then try to open a web file in `Help -> Mogan`. The following debugging meesage will be printed in the console.
```
TeXmacs] debug-io, curl --user-agent TeXmacs-2.1.1 https://gitee.com/XmacsLabs/mogan/raw/main/TeXmacs/doc/about/xmacs/2019年全国高中数学联合竞赛一试试题A卷.tm --output /home/sadhen/.Xmacs/system/tmp/93518/tmp_1951389520
```
The current impl actually work only on macOS and Linux. In this pull request, I decide only replace the curl command line invoke with libcurl. And later, I will submit the follow-up pull requests to:
+ make it work on Windows
+ correctly handle the exceptions
> Use libcurl instead for invoke the curl command line

- CMakeLists.txt
sub pr of https://github.com/XmacsLabs/mogan/pull/123
Qt6 requires c++17
> upgrade c++ standard to 17

- src/Plugins/Qt/qt_gui.cpp
Give an option like Typora,
But now, only support `copy image to current folder`.
add the following scheme code to your `init-buffer.scm`
```scm
(define (notify-julia-syntax2 var val)
())
(define-preferences
("copy image to current folder" "on" notify-julia-syntax2))
```
Is there a more elegant way to change user preferences? 😭
I just want to provide an option
separate binary data and plain text.
> copy image to current folder when pasting image from the clipboard

- CMakeLists.txt
sub pr of https://github.com/XmacsLabs/mogan/pull/123
The target-based CMake style can manage headers and libraries automatically.
> CMake: remove headers

- TeXmacs/progs/generic/generic-menu.scm
before
after 
the code from `edit-menu.scm`
why do the following codes cause crashes when removing them?
```
(when (or (selection-active-any?)
(and (in-graphics?)
(graphics-selection-active?)))
```
> [no ci] add copy cut paste to context menu

- CMakeLists.txt
- src/Plugins/MacOS/mac_utilities.mm
- src/Plugins/Qt/QTMApplication.hpp
- src/Plugins/Qt/QTMMenuHelper.cpp
- src/Plugins/Qt/QTMPrintDialog.hpp
- src/Plugins/Qt/QTMPrinterSettings.cpp
- src/Plugins/Qt/QTMPrinterSettings.hpp
- src/Plugins/Qt/QTMScrollView.cpp
- src/Plugins/Qt/QTMStyle.cpp
- src/Plugins/Qt/QTMWidget.cpp
- src/Plugins/Qt/qt_chooser_widget.cpp
- src/Plugins/Qt/qt_font.cpp
- src/Plugins/Qt/qt_gui.cpp
- src/Plugins/Qt/qt_pipe_link.cpp
- src/Plugins/Qt/qt_renderer.cpp
- src/Plugins/Qt/qt_simple_widget.cpp
- src/Plugins/Qt/qt_ui_element.hpp
- src/Plugins/Qt/qt_utilities.cpp
- src/Plugins/Qt/qt_utilities.hpp
- src/Plugins/Qt/qt_window_widget.cpp
- tests/CMakeLists.txt
Build TeXmacs with Qt6
maybe some bugs, we need more tests.
All changes do not affect the Qt5 version.
set `CMAKE_PREFIX_PATH` to Qt6 cmake path
```
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=/Users/pikachu/Qt/6.3.0/macos/lib/cmake ..
make -j4
```
There are no equivalent replacements for the following changes.
- QPrinter::setPaperSize
no `QPrinter::DevicePixel` in QPageSize
on TeXmacs qt6 branch, it just print log
```
if (DEBUG_CONVERT) debug_convert << "no dpi or size informations!!" << LF;
```
- QWheelEvent::delta
- QApplication::globalStrut
on TeXmacs qt6 branch, a fixed value assigned
```
calcSize = QSize(2, 2);
```
After merge https://github.com/XmacsLabs/mogan/pull/135
We can see
> initial support for Qt 6

- src/Typeset/Env/env_semantics.cpp
Fixes the choice typesetting bug, here is the demo doc:
```
<TeXmacs|2.1.1>
<style|<tuple|generic|chinese>>
<\body>
<math|<choice|<tformat|<table|<row|<cell|>>|<row|<cell|>>>>>>
</body>
<\initial>
<\collection>
<associate|page-medium|paper>
</collection>
</initial>
```
closes #110
> Use math font in math mode

- src/Plugins/Qt/qt_file.cpp
- src/Plugins/Qt/qt_file.hpp
- src/System/Files/file.cpp
- tests/System/Files/file_test.cpp
IO code in https://github.com/XmacsLabs/mogan/blob/main/src/System/Files/file.cpp is not in a good quality. We should replace it using Qt.
Without it crashes on Windows because `read_directory` on Windows returns messy code.
> Re-impl read_directory using Qt

- src/Typeset/Env/env_semantics.cpp
This reverts commit 8da61ab5cf01bf2500e5852dda6ef6d76f65a220.
> Revert "Use math font in math mode (#176)"

- src/Edit/Interface/edit_interface.cpp
- src/Edit/Interface/edit_interface.hpp
This will save us from the Chinese input method disorder.
> Update focus toolbar only when there is env_change

- TeXmacs/progs/texmacs/texmacs/tm-files.scm
Links open rules:
1. If it is a http/https/ftp/... link
+ if it ends with tm, open it in Mogan Editor
+ else just open it in web browser
2. If it is a local file, open it in Mogan Editor
Before, the rules work fine when we are in a local file buffer but it failed to work in a remote file buffer.
With the PR merged, the rules is the same for both local and remote files.
Fixes #234
> [no ci] Open links in remote files as in local files

- src/Plugins/Qt/QTMMenuHelper.cpp
Fixes #222 
It fixes the crash issue, and we still need to click twice to open the document searching window.
> Qt: fix QTMLineEdit crash when using Input Method

- src/Edit/Interface/edit_interface.cpp
git grep `got_focus=`, we can find all assignment of got_focus
> Using got_focus instead of the bitwise operator

- src/Data/Convert/Texmacs/fromtm.cpp
- src/Data/Convert/Texmacs/totm.cpp
The reader is compatible with the previous reader.
For the writer, we provide the option `tm format with utf8`, it will be default to off for GNU TeXmacs.
> option for TM format with UTF8 support

- misc/CMakeLists.txt
By default GZIP add timestamp and filename to compressed documents, which harms
the reproducibility of build. Use "-n" flags to disable it.
> Don't add timestamp and filename to gzip-compressed man pages.

- README.md
Add
* https://aur.archlinux.org/packages/mogan
> [no ci] Introduction to aur package

- CMakeLists.txt
If both Qt5 and Qt6 installed on machine, mogan would automatically linked Qt6 library always. 
Support for Qt6 is experimental, and Qt6 is not backward compatible with Qt5. It's better for mogan to using Qt6 explicitly.
> Using Qt6 explicitly

- src/Plugins/Curl/curl.cpp
eliminate warning: logical not is only applied to the left hand side of this comparison
> eliminate warning

- .github/workflows/package-macos.yml
- packages/macos/package.sh
Rewrite `packages/macos/package.sh` for better error handling, robust structure and self-explainable code.
- CI: https://github.com/pan93412/mogan/actions/runs/3594111085/
> refactor(packages/macos): Cleaner Structure

- packages/macos/package.sh
“Copy Assets” is a optional step, and should not break the subsequent commands. `|| true` indicates `bash` to not stop at this command.
This fixes #395
- Proof CI: <https://github.com/pan93412/mogan/actions/runs/3597383535> (passed)
- The CI of this commit: <https://github.com/pan93412/mogan/actions/runs/3597549087> **Passed!**
> fix(package/macos): Don't break on `copy_assets`

- .github/workflows/ci-xmake.yaml
- packages/windows/Xmacs.iss.in
- xmake.lua
This ci will be triggered by pushing tag. Cache qt environment to accelerate ci execution. Use windeploy twice to avoid `Qt5Test` appears in installer.
Binary dependencies is stored in [XmacsLabs/mogan-dependencies](https://github.com/XmacsLabs/mogan-dependencies)
* #116 
* #127 
* #128 
* #129
> Add package ci for windows 2h

- packages/windows/Xmacs.iss.in
This PR changes the format of the version that the Windows installer writes to the uninstall registry key from `v1.1.2` to `1.1.2`, so it will align with the version string on Windows prior to 1.1.0 and other platforms (macOS, etc.). This will not affect current users.
By the way, the `VersionInfoTextVersion` property has been deprecated after Windows 98. It can be replaced by `VersionInfoVersion`.
https://jrsoftware.org/ishelp/index.php?topic=setup_versioninfotextversion
> Change version format on Windows

- src/Texmacs/Texmacs/texmacs.cpp
There is a strange line in `texmacs.cpp` which reset the icon. I've now fixed it to point to the new icon. I do not understand why this is necessary. I guess we can remove that line since the application icon should be specified in the metadata and not in the code (unless one what to change it programmatically)
> Fix the icon in the Dock for Mac

- .github/workflows/ci-xmake.yml
Main branch of action to set up mingw is egor-tensin/setup-mingw
> Eliminate warnings caused by action of mingw setup.

- .github/workflows/ci-xmake-wasm.yml
- src/System/config.h.xmake
- xmake.lua
https://doc.qt.io/qt-6/wasm.html#installing-emscripten
`mogan.js` should be patched as below:
```js
var createQtAppInstance = (() => {
var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
return (
function(createQtAppInstance) {
createQtAppInstance = createQtAppInstance || {};
/* content generated by emsdk */
return createQtAppInstance.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
module.exports = createQtAppInstance;
else if (typeof define === 'function' && define['amd'])
define([], function() { return createQtAppInstance; });
else if (typeof exports === 'object')
exports["createQtAppInstance"] = …
```
> [143] bump qt version and emsdk version

- docs/guide/Develop_on_Windows.md
- docs/zh/guide/Develop_on_Windows.md
修改了mogan\docs\zh\guide\Develop_on_Windows.md和mogan\docs\guide\Develop_on_Windows.md
> improve the Windows docs

- xmake.lua
since version of mingw used to build mogan may differs from version of Qt, tell windeployqt to use lib from mingw may break ABI compability.
> [8_1] deploy cxx runtime from qt

- TeXmacs/progs/graphics/graphics-main.scm
In addition, there are still some issues with the functionality of 23_20. I have browsed the code repository, but I couldn't figure out why the menu button sometimes doesn't change to a dark color. Given the work schedule of OSPP, I will temporarily suspend this task.
Currently, as long as users follow the normal procedure, there won't be any inconsistencies. However, if a user is in the circle drawing mode and clicks the circle button again, it will enter the mode for setting properties. At this point, if the user clicks the circle button again, it will return to the circle drawing mode. The mode switching works fine. However, the circle button does not change to a dark color.
> [23_20] Fix a bug that would cause an infinite loop

- src/System/config.h.xmake
- xmake.lua
This add compilation switch to toggle experimental feature described in #936 , added switch is listed below:
* `experimental`: `EXPERIMENTAL`
* `sanity-checks`: `SANITY_CHECKS`
* `use-exceptions`: `USE_EXCEPTIONS`
```
xmake config --experimental=y --sanity-checks=y --use-exceptions=y
```
> [49_1] add compilation switch to toggle experimental feature

- xmake.lua
Because we are using `add_forceincludes`.
https://xmake.io/#/manual/project_target?id=targetadd_forceincludes
> [32_8] set minimal xmake version to 2.8.2

- TeXmacs/progs/texmacs/texmacs/tm-files.scm
`url-test? u "c"` returns `true` when u does not exist before, we change the semantics recently.
close #1005
> [53_7] Replace (url-test? u "c") with url-exists?

- xmake.lua
To simplify the xmake build definition.
Use table.contains to simplify build definition
> [32_6] xmake: simplify cpp test targets

- misc/xmake/packages.lua
Use lolly 1.2.6 to fix `is_directory(url("/"))` on wasm.
+ [x] bump lolly to 1.2.6
> [53_11] use lolly 1.2.6

- src/Mogan/Draw/draw.cpp
https://github.com/XmacsLabs/mogan/commit/7ebc87ff6518103ca5705c39ad398edea1c929e6 breaks the mogan draw app.
This pr will fix it.
> [53_7] draw: init_tbox

- TeXmacs/progs/doc/apidoc-collect.scm
- TeXmacs/progs/kernel/texmacs/tm-plugins.scm
- TeXmacs/progs/texmacs/texmacs/tm-tools.scm
- src/Data/Document/new_style.cpp
- src/Graphics/Fonts/font_database.cpp
- src/Mogan/Code/code.cpp
- src/Mogan/Draw/draw.cpp
- src/Mogan/Research/research.cpp
- src/Scheme/L2/glue_misc.lua
- src/System/Boot/init_texmacs.cpp
- src/System/Boot/init_upgrade.cpp
- src/System/Misc/data_cache.cpp
- src/System/Misc/tm_sys_utils.cpp
- src/System/Misc/tm_sys_utils.hpp
Use `(get-tm-cache-path)` instead of `(string->url "$TEXMACS_HOME_PATH/system/cache")` to simplify the change of the TeXmacs cache directory.
> [56_1] Use get-tm-cache-path instead hard coded path

- plugins/pdf/progs/init-pdf.scm
Incorrectly loading a pdf without attachments and detaching the attachment returns false. In this case, no error handling is performed and the entire program will crash. Add error handling to prevent crashes.
> [29_6] add error handling for pdf->texmacs

- xmake.lua
Simplify xmake.lua and avoid setting linker flag manually.
see also https://github.com/xmake-io/xmake/discussions/3910
> [49_5] use qt.console instead of -mconsole

- TeXmacs/plugins/pdf/progs/init-pdf.scm
In project 29, it is necessary to add conversion methods for pdf format and tm format, but the conversion method from tm to pdf is actually a pdf export method, so the method implemented here is useless
> [29_7] remove dead code

- src/Plugins/Pdf/pdf_hummus_extract_attachment.cpp
- tests/Plugins/Pdf/pdf_make_attachment_test.cpp
Change the traversal method of tm_tree from loop to recursion, and split the style tree and image tree processing into small functions to improve code readability and neatness
> [29_7] refactor get_linked_file_paths

- src/Plugins/Pdf/pdf_hummus_extract_attachment.cpp
Change the traversal method of tm_tree from loop to recursion, and split the style tree and image tree processing into small functions to improve code readability and neatness
> [29_7] refactor replace_with_relative_path

- src/System/Files/image_files.cpp
Follow-up of https://github.com/XmacsLabs/mogan/pull/1197
> [41_2] Fix ps_load ramdisc url on macOS

- TeXmacs/progs/check/check-master.scm
- TeXmacs/progs/utils/cite/cite-sort-test.scm
- TeXmacs/progs/utils/cite/cite-sort.scm
Merge continuous citing indices, close #166 :
| Origin | Merged |
|--------|--------|
| [1, 2, 3] | [1-3] |
| [1, 2, 3, 4, 5] | [1-5] |
| [1, 3, 4, 5, 7] | [1, 3-5, 7] |
| [1, 2, 4, 5] | [1, 2, 4, 5] | 
Users should add `cite-sort` style package explicitly to enable this feature.
[Origin patch is provided by Zhengfei Hu(hammer)](https://savannah.gnu.org/patch/?10339) @hammerfunctor
> [63_2] Merge contiguous indices for sorted bib items

- TeXmacs/progs/graphics/graphics-markup.scm
- TeXmacs/progs/graphics/graphics-utils.scm
Fix a bug about drawing arc. 
Bug: if 3 points in one line, it could be a semi-circle. But in previous version, we can not get a semi-circle. The program will give a line. Now it's fixed. We can get a semi-circle.
> [23_27] Draw arc: fix bug when 3 points in one line

- src/Plugins/Qt/qt_chooser_widget.cpp
On macOS, `File -> Open` when the current-buffer is scratch, the current dir will be root directory. It should be set to homedir.
> [71_23] Open file defaults to home path when current dir is root

- xmake/tm2html.lua
fix compiling error about MT in `tm2html` under windows
> [24_6] fix compiling error under windows

- src/Graphics/Fonts/font.hpp
- src/Graphics/Fonts/font_database.cpp
- src/Plugins/Freetype/tt_file.cpp
Before
```
TeXmacs] std-bench, Task 'tt_locate Songti.pfb' took 1057 ms
TeXmacs] std-bench, Task 'tt_locate Songti.ttf' took 23 ms
TeXmacs] std-bench, Task 'tt_locate Songti.ttc' took 19 ms
TeXmacs] std-bench, Task 'tt_font_exists Songti' took 1099 ms
```
Now
```
TeXmacs] std-bench, Task 'tt_locate Songti.ttc' took 16 ms
TeXmacs] std-bench, Task 'tt_font_exists Songti' took 270 ms
```
or
```
TeXmacs] std-bench, Task 'tt_locate Songti.ttc' took 17 ms
TeXmacs] std-bench, Task 'tt_font_exists Songti' took 36 ms
```
> [11_17] Use local font_rev_table to speedup tt_font_exists

- src/Edit/Modify/edit_dynamic.cpp
…
Importing revision 14129, fixes broken `include` macro inserted from slash command.
> [47_5] Fix bug: Inserting "include" macro does not work from keyboard

- src/Kernel/Types/rectangles.cpp
- src/Kernel/Types/rectangles.hpp
- src/Typeset/Boxes/Basic/boxes.cpp
- src/Typeset/Boxes/Composite/concat_boxes.cpp
- src/Typeset/Bridge/impl_typesetter.hpp
- src/Typeset/Bridge/typesetter.cpp
- src/Typeset/boxes.hpp
This reverts commit 5f8724a21742dcc1fc87255bc88ac2ba44e73744.
> [7_2] Revert: Use long array instead of long list to avoid stackoverflow

- TeXmacs/progs/generic/generic-kbd.scm
- src/Plugins/Qt/QTMWidget.cpp
- src/Plugins/Qt/qt_utilities.cpp
- src/Plugins/Qt/qt_utilities.hpp
+ Refactor keyboard handling with printable ascii characters
+ Fix `Command-+` on macOS to zoom in
+ Shortcuts in Input Method is not handled in this pull request
> [59_13] Refactor keyboard handling on printable ascii characters with/without modifiers

- src/Data/Convert/Texmacs/fromtm.cpp
- src/Edit/Editor/edit_main.cpp
- src/Plugins/Pdf/pdf_hummus_renderer.cpp
- tests/Data/Convert/convert_test.cpp
Insert abstraction into a document, and add keywords with focus toolbar. Then export this document to PDF, open exported PDF in browser, and open "document properties" dialogue.
> [68_8] extract keywords from abstract-data and add them to exported pdf

- TeXmacs/progs/texmacs/menus/edit-menu.scm
- src/Plugins/Ispell/ispell.cpp
1. Add nil check on `sc->ln`
2. use is_empty instead of ` == ""`
3. Enable the `Edit->Spell` menu
> [7_5] Fix spell crash when aspell and hunspell is not available

- TeXmacs/langs/natural/dic/english-new.scm
- TeXmacs/plugins/lang_zh_CN/data/from_en_US.scm
- TeXmacs/progs/version/version-menu.scm
Fix translate conflict between Version->Grain->Block menu and <block> tag.
> [44_4] separate Version->Grain->Block from <block>

- src/Plugins/Git/git.cpp
Fix error caused by slash`\`. When a file under some directory is loaded by libgit on windows, slash is used rather than backslash`/`, therefore libgit treat that slash as regular filename.
> [44_8] fix error when reading file in subdirectory on windows

- src/Data/Convert/Texmacs/fromtm.cpp
improve parsing speed of tm snippets, which may take 1.5s when parsing a short document.
> [66_5] improve parsing speed of tm snippets

- src/Plugins/Qt/qt_utilities.cpp
- tests/Plugins/Qt/qt_utilities_test.cpp
Affected shortcuts:
```
A-=
A--
A-[
A-]
A-\
A-;
A-'
A-<
A->
A-/
```
> [59_22] macOS: Fix shortcuts of option with non-alphanum keys

- src/Edit/Interface/edit_keyboard.cpp
Related commits:
+ https://github.com/XmacsLabs/mogan/commit/b5c2160af760ad9b3149b719d78f06d8d9036a0d
> [59_24] Fix for the escape key

- src/Graphics/Fonts/translator.cpp
- src/Scheme/L2/glue_lolly.lua
- src/System/Boot/init_texmacs.cpp
- xmake/packages/l/lolly/xmake.lua
- xmake/vars.lua
This is a breaking change.
Before
```
(string->url "xxx") <=> (url-unix "xxx")
```
Now:
```
(string->url "xxx") <=> (system->url "xxx")
```
And `string->url` is the implicit conversion from string to url in Scheme or C++.
> [75_12] Upgrade to lolly 1.4.0

- src/Plugins/Pdf/pdf_hummus_extract_attachment.cpp
- src/Plugins/Pdf/pdf_hummus_make_attachment.cpp
- always write catalog (which was reason of a bug with newer version of the PDF output) 
- take care of embedded images
- the Catalog of the modified PDF was not written in all occasions, this was due to wrong use of the interface of the PDF Writer extenders
- images embedded in the document should be ignored when gathering the external attachments paths
- export/import a file with PDF version > 1.4 and with embedded images
> [29_9] Fix for a couple of bugs: 

- xmake/packages/l/lolly/xmake.lua
- xmake/packages/m/moebius/xmake.lua
- xmake/vars.lua
as title
bump version for lolly and moebius, keep them up-to-date after the string->lolly_string attempt
+ [x] macOS
+ [x] Windows
+ [ ] Linux
```
xmake b research
xmake r research
```
> [75_21] Upgrade to lolly 1.4.17, moebius 0.1.17

- TeXmacs/plugins/binary/progs/binary/aspell.scm
- TeXmacs/plugins/binary/progs/binary/common.scm
- TeXmacs/plugins/binary/progs/binary/convert.scm
- TeXmacs/plugins/binary/progs/binary/gs.scm
- TeXmacs/plugins/binary/progs/binary/hunspell.scm
- TeXmacs/plugins/binary/progs/binary/inkscape.scm
- TeXmacs/plugins/binary/progs/binary/pdftocairo.scm
- TeXmacs/plugins/binary/progs/binary/python3.scm
- TeXmacs/plugins/binary/progs/binary/rsvg-convert.scm
- TeXmacs/tests/tm/61_3.tm
+ impl common routine `find-binary` in the following order:
1. Check `plugin:binary:<binary-name>` first
2. Check `(binary-gs-candidates)` secondly
3. Check binary under the PATH (excluding im-proper PATH like `C:/Windows/System32`)
+ Migrate all binary plugins to `(find-binary)`
+ Added two path candidates for ImageMagick convert on Windows
+ Fix convert bug on Windows
+ Reduce duplicated code
+ [x] macOS
+ [x] Windows
+ [ ] Linux
Open `TeXmacs/tests/tm/61_3.tm` and evaluate the Scheme sessions.
> [61_3] Binary plugins: find-binary

- bin/build_website
- package.json
- yarn.lock
Upgrade vitepress to 1.0.1 for mogan.app
use the stable release
```
yarn install
bin/build_website
bin/preview_website
```
> [5_2] Doc: use vitepress 1.0.1

- TeXmacs/tests/tm/68_11.tm
- src/Plugins/Pdf/pdf_image.cpp
- src/System/Files/image_files.cpp
- src/System/Files/web_files.cpp
1. Error handling for `hummus_pdf_image_size`
2. Unify the conversion from x to png using scheme (remove the call to the imagemagick C++ routine)
3. Only `get_from_web` when the HTTP status code is 200
The error message for PDF images is confusing. Improve the error handling slightly.
Open `TeXmacs/tests/tm/68_11.tm`.
> [68_11] Better error handling for PDF images

- packages/debian/package.sh
Using relative INSTALL_DIR, it will be installed to `$(projectdir)/xmake/debian/mogan-research`. This pull request fixed the issue and will install it to `$(projectdir)/debian/mogan-research`
```
./packages/debian/package.sh
```
> [3_5] Fix INSTALL_DIR on Debian and Ubuntu

- src/Data/String/converter.cpp
- src/Data/String/converter.hpp
- xmake/packages.lua
- xmake/packages/l/lolly/xmake.lua
- xmake/vars.lua
+ Upgrade lolly to 1.4.18
+ as_int now support `+1`, `+10` by @jingkaimori 
+ Use string_u8 in converter
string_u8 as an alias of string is just a indicator.
No need to test.
> [75_22] Upgrade lolly to 1.4.18 and use string_u8 in converter

- src/Plugins/Qt/qt_gui.cpp
```
warning: ‘Qt::AA_UseHighDpiPixmaps’ is deprecated: High-DPI pixmaps are always enabled. This attribute no longer has any effect. [-Wdeprecated-declarations]
185 |   qApp->setAttribute (Qt::AA_UseHighDpiPixmaps);
|                          ^~~~~~~~~~~~~~~~~~~~
```
code cleaning
No need.
> [65_10] Qt: deprecate Qt::AA_UseHighDpiPixmaps

- TeXmacs/packages/beamer/presentation.ts
- TeXmacs/tests/tm/77_12_16x9.tm
- TeXmacs/tests/tm/77_12_4x3.tm
Switch to `16:9` when switching to beamer style for a new TeXmacs doc.
`16:9` is more widely adopted than `4:3`
+ Create a new document, and switch to beamer style, check the page type in the focus toolbar (should be 16:9)
+ Open `TeXmacs/tests/tm/77_12_4x3.tm`, the page type should be `4:3`
+ Open `TeXmacs/tests/tm/77_12_16x9.tm`, the page type should be `16:9`
> [77_12] Default: page-type defaults to 16:9 when switching to beamer style

- TeXmacs/progs/texmacs/texmacs/tm-files.scm
If the buffer is in beamer style and in book page rendering, `fit-to-screen-width` after `open-buffer`.
Improve user experience of beamer style.
+ Open `TeXmacs/doc/about/mogan/beamer.en.tm`, it will `fit-to-screen-width`.
+ Open `TeXmacs/doc/about/mogan/research.en.tm`, nothing happened.
> [77_9] Beamer: fit-to-screen-width after open-buffer of beamer tm doc in book page rendering

- TeXmacs/progs/texmacs/texmacs/tm-view.scm
`fit-to-screen-width` after clicking `View->Presentation mode`
Do not need to zoom out. Before it is `fit-to-screen`, we need to zoom out to make it work.
Open `TeXmacs/doc/about/mogan/beamer.en.tm` and click `View->Presentation mode`.
And then, quit the Presentation mode, and switch to the Slide page rendering, and click `View->Presentation mode` again.
> [77_13] Beamer: fit-to-screen-width after entering presentation-mode

- TeXmacs/plugins/octave/octave/convert/mat2scm.m
- TeXmacs/tests/tm/7_11.tm
- bin/research
Fix typesetting failure caused by `ones (0)` in the Octave.
This pull request fixed the bug in the Octave side. It does not fix the bug in the typesetter.
Fixing the bug in the typesetter is much harder. Fix the bug first and then find the best way to fix it.
See `TeXmacs/tests/11_7.tm`.
> [7_11] Fix typesetting failure caused by `ones (0)` in the Octave session

- src/Edit/Editor/edit_main.cpp
- src/System/Files/image_files.cpp
- src/System/Files/image_files.hpp
+ Deprecate `call_imagemagick_convert` when converting image formats to pdf format
+ Deprecate `call_imagemagick_convert` when exporting the selected document
Unify the image format conversion to image plugin.
Make sure `(has-binary-convert?)` is true and then:
+ Export `TeXmacs/tests/tm/38_8.tm` to PDF
+ Export the selected part in `TeXmacs/tests/tm/38_8.tm` as the supported image format
> [38_8] Deprecate the usage of call_imagemagick_convert

- packages/debian/control.in
Use virtualbox to install Ubuntu 24.04, and install mogan-research v1.2.5.1, you will find that it fails to launch. `apt install qt6-qpa-plugins` will fix the bug.
Fix the missing xcb error by add `qt6-qpa-plugins` as a dep
```
./packages/deb/package.sh
```
And check if `qt6-qpa-plugins` is a dep of the mogan-research deb.
> [3_5] Ubuntu: set qt6-qpa-plugins as the dep

- xmake.lua
add_syslink on Windows for Surface, otherwise, it failed to link libmogan
Config and build on MS Surface devices.
```
xmake b research
```
> [73_20] xmake: add the missing syslink on Windows surface

- src/Scheme/L2/glue_lolly.lua
Fix the glue `url-unix`.
Before of the semantic change in lolly 1.4.0. The default constructor of url means `system->url` now.
+ [x] Windows
+ [ ] macOS
+ [ ] Linux
Test if the maxima or octave plugin works.
> [75_12] Fix url_unix since lolly 1.4.0

- TeXmacs/plugins/octave/progs/binary/octave.scm
as title
`/snap/bin/octave-cli -p /usr/share/xxx.m` does not work 
Build and install deb, try to launch octave the via the snap installed one.
> [67_2] Octave: remove the snap installed one from binary candidates

- TeXmacs/plugins/maxima/progs/binary/maxima.scm
as title
`/snap/bin/maxima -p /usr/share/xxx.lisp` does not work 
Build and install deb, try to launch maxima the via the snap installed one.
> [60_8] Maxima: remove snap installed one from binary candidates

- src/Data/Convert/Texmacs/fromtm.cpp
- src/Data/String/converter.cpp
- src/Data/String/converter.hpp
- src/Data/String/unicode.cpp
- src/Data/String/universal.cpp
- src/Data/String/wencoding.cpp
- src/Graphics/Fonts/smart_font.cpp
- src/Plugins/Freetype/unicode_font.cpp
- src/Plugins/Freetype/unicode_math_font.cpp
- src/Plugins/Tex/parsetex.cpp
- src/System/Language/hyphenate.cpp
- xmake/packages/l/lolly/xmake.lua
- xmake/vars.lua
+ Migrate `decode_from_utf8`, `encode_as_utf8` to lolly
Lolly is the kernel part of Mogan. UTF-8 related routines should be maintained in lolly.
CI.
> [75_23] Upgrade to lolly 1.4.19

- src/Plugins/Qt/QTMMenuHelper.cpp
https://doc.qt.io/qt-6/qvariant-obsolete.html#canConvert-1
> `bool QVariant::canConvert(int targetTypeId) const`
> This function is deprecated since 6.0. We strongly advise against using it in new code.
> This is an overloaded function.
> Use canConvert(QMetaType(targetTypeId)) instead.
CI
> [65_11] Qt 6: deprecate QVariant::canConvert(int targetTypeId)

- xmake/packages/l/lolly/xmake.lua
- xmake/packages/m/moebius/xmake.lua
- xmake/vars.lua
+ moebius `0.1.17 -> 0.1.18` (the alias: tree_u8)
+ lolly `1.4.19 -> 1.4.20` (minor fix on string_vew.hpp)
Regular upgrade of deps.
CI.
> [75_24] Upgrade to moebius 0.1.18 and lolly 1.4.20

- .github/workflows/cd_research_on_macos.yml
- .github/workflows/ci-xmake-macos.yml
as title
macos-11 runner is deprecated
CICD.
> [73_33] Upgrade CICD from macOS 11 to macOS 12

- src/Plugins/Pdf/pdf_hummus_extract_attachment.cpp
Use `is_none` instead of `u != url ()`
`u != url ()` is not a good way to express `!is_none`, `url () == url_none ()` is a hidden rule of the url class.
CI
> [29_9] Use is_none instead of u != url ()

- TeXmacs/tests/tm/66_6.tm
- src/Data/Convert/Generic/input.cpp
- src/Data/Convert/Generic/input.hpp
- src/Data/Tree/tree_traverse.cpp
- src/Data/Tree/tree_traverse.hpp
This is a protocol change, it brings new feature which is absent for GNU TeXmacs <= 2.1.4.
Add `scheme_u8` input mode for UTF-8 Scheme tree.
Use UTF-8 Scheme tree as the protocol for plugins.
See `TeXmacs/tests/tm/66_6.tm`
How it works:
1. `66_6.tm` is encoded in cork
2. `python-serialize` in `init-python.scm` will convert the cork encoded tree into UTF-8 python code snippet
3. The python interpreter evaluates the UTF-8 python code snippet and generate the UTF-8 output
4. The output is captured by the "fragile" protocol defined in `input.cpp`
`tree_utf8_to_cork` is an adhoc impl, it will be migrated to moebius later. Please focus on the protocol design to review this pr. In scala snippet, `tree_utf8_to_cork` should be implemented as `tree.map (utf8_to_cork)`. The C++'s syntax is too ugly …
> [66_6] Protocol: scheme_u8 for UTF-8 Scheme tree

- TeXmacs/plugins/binary/progs/binary/aspell.scm
- TeXmacs/plugins/binary/progs/binary/common.scm
- TeXmacs/plugins/binary/progs/binary/convert.scm
- TeXmacs/plugins/binary/progs/binary/hunspell.scm
- TeXmacs/plugins/binary/progs/binary/identify.scm
- TeXmacs/plugins/binary/progs/binary/inkscape.scm
- TeXmacs/plugins/binary/progs/binary/pdftocairo.scm
- TeXmacs/plugins/binary/progs/binary/rsvg-convert.scm
- TeXmacs/plugins/maxima/progs/binary/maxima.scm
- TeXmacs/plugins/octave/progs/binary/octave.scm
- TeXmacs/tests/tm/61_3.tm
+ Common routines `(version-binary)`
Return the first non-empty line as the version line for the binary.
Binary version is needed for all binaries.
Open `TeXmacs/tests/tm/61_3.tm`.
> [61_3] Binary: version-binary-xyz impl

- TeXmacs/progs/generic/search-widgets.scm
Fix replace-one and replace-all on the replace toolbar.
bug fix
Click `Help->Welcome`, and click `Edit->Replace` and then replace `<from>` with `<to>`, using the Enter key, it should work fine. Using the mouse to click the button, it should work fine too with this pull request.
> [20_9] Replace: fix replace-one and replace-all on replace-toolbar

- TeXmacs/plugins/binary/progs/binary/common.scm
- TeXmacs/tests/tm/61_3.tm
Added two options of `plugin:binary:xyz`:
+ `candidates-only`: only resolve candidates, if not found, just return `(url-none)`
+ `off`: disable the binary plugin, just return `(url-none)`
Both of the options are for the security reason:
+ `candidates-only`: trust the candidates
+ `off`: do not trust the binary
See `TeXmacs/tests/tm/61_3.scm`.
> [61_3] Binary: candidates-only and off option for a binary

- TeXmacs/plugins/binary/progs/binary/common.scm
- TeXmacs/plugins/binary/progs/binary/gs.scm
- TeXmacs/plugins/binary/progs/binary/python3.scm
Re-impl finding binary in sys path.
Related pull request: https://github.com/XmacsLabs/mogan/pull/1744
We must keep the consistency of `binary-id`. In the previous impl, the binary-id for python3 is `python3` on linux and macOS, and is `python` on windows.
Open `TeXmacs/tests/tm/61_3.tm`
> [61_3] Binary: improve impl for finding binary in sys path

- src/Plugins/Qt/QTMWidget.cpp
Disable IM preedit on Linux to speedup.
Menu entry to turn on/turn of IM pre-editing will be implemented in another pull request.
Performance tuning.
Why not turn it on by default on macOS and Windows: because input via speech is available on Windows and macOS.
+ [x] Linux
+ [ ] macOS
+ [ ] Windows
> [79_2] IM: disable preedit by default on linux to speedup editing

- docs/guide/OSPP_2024_HTML.md
Preview: https://github.com/XmacsLabs/mogan/blob/da/5_23/ospp_pandoc/docs/guide/OSPP_2024_HTML.md
OSPP 2023 Projects:
+ https://mogan.app/guide/OSPP_2023_Mogan_Draw.html
+ https://mogan.app/guide/OSPP_2023_PDF.html
> [5_23] OSPP 2024 Project: Conversion from TeXmacs format to HTML and DOCX

- TeXmacs/plugins/image/progs/image/svg.scm
as title
It does not work on Debian 12
```
> convert TeXmacs/misc/pixmaps/modern/24x24/main/tm_cloud.svg /tmp/test.pdf                                                                                                       
convert: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/426.
Exception: convert exited with 1
```
No need to test.
> [38_7] svg: remove imagemagick as the converter to ps/pdf

- src/Typeset/Concat/concat_active.cpp
It was a fix on branch `lts-125`.
For `branch-1.2`, since we have upgraded to lolly 1.4.x, the implicit conversion from string to url is using url_system now. This pull request is for using url_system explicitly but not a fix now. Let us keep the pull request title in `branch-1.2`.
+ [x] Linux
+ [x] Windows
+ [ ] macOS
Insert a linked image with absolute path to see if it is rendered correctly.
> [75_12] Fix rendering of linked image on Windows using absolute path

- TeXmacs/plugins/cite/LICENSE
- TeXmacs/plugins/cite/README.md
- TeXmacs/plugins/cite/doc/cite.en.tm
- TeXmacs/plugins/cite/doc/global.bib
- TeXmacs/plugins/cite/packages/contrib/cite-sort.ts
- TeXmacs/plugins/cite/progs/contrib/cite/cite-sort-test.scm
- TeXmacs/plugins/cite/progs/contrib/cite/cite-sort.scm
Move cite-sort related code to XmacsLabs/cite and make cite v1.0.0 built-in
It is for the plugin-center.
Open `Help->Plugins->Cite`.
> [61_4] Style: cite v1.0.0

- src/Data/Document/new_style.cpp
- src/Data/Document/new_style.hpp
- src/Edit/Editor/edit_typeset.cpp
- src/System/Files/tm_file.cpp
- src/System/Files/tm_file.hpp
- tests/System/Files/tm_file_test.cpp
+ Fix the search result orders for `search_sub_dirs`
+ Side effect: user installed fonts will override the system fonts (it is a fix on the wrong behavior)
+ Cache all styles by content digests
+ Check `Debug->io` for the debug info of style resolving
Here is the expected order to load a style or package:
+ `$TEXMACS_HOME_PATH/styles`
+ `$TEXMACS_PATH/styles`
+ `$TEXMACS_HOME_PATH/plugins/xxx/styles/`
+ `$TEXMACS_PATH/plugins/xxx/styles`
+ `$TEXMACS_HOME_PATH/packages`
+ `$TEXMACS_PATH/packages`
+ `$TEXMACS_HOME_PATH/plugins/xxx/packages/`
+ `$TEXMACS_PATH/plugins/xxx/packages/`
Content digests should be adopted for modification on user defined styles/packages.
Try customizing https://github.com/XmacsLabs/physics
> [56_5] Cache styles by content digest

- TeXmacs/tests/tm/27_2_graphics.tm
- src/Edit/Replace/edit_select.cpp
When using mouse to select the graphics area, it will enter the graphics mode.
+ `selection_active_any ()` is true
+ `inside_active_graphics ()` is true
After entering the graphics mode, and we select the graphics objects:
+ `selection_active_any ()` is false
+ `inside_active_graphics ()` is true
For most cases with selections:
+ `select_active_any ()` is true
+ `inside_active_graphics ()` is false
see `27_2_graphics.tm`
> [27_2] Graphics: fix copy/cut on selection via mouse

- TeXmacs/plugins/lang/dic/en_US/zh_CN.scm
- TeXmacs/progs/kernel/texmacs/tm-modes.scm
- TeXmacs/progs/texmacs/menus/main-menu.scm
- TeXmacs/progs/texmacs/menus/view-menu.scm
- TeXmacs/progs/texmacs/texmacs/tm-view.scm
as title
Quitting `View->Header bars` is too hard. One need to know the `Ctrl+Left click` trick.
Using `View->Focus mode`, just quit the focus mode via the context menu triggered by right click.
Click `View->Focus mode`, and right click and then uncheck `Focus mode` to quit it.
> [71_38] Add View->Focus mode, remove View->Header bars

- TeXmacs/progs/texmacs/texmacs/tm-files.scm
Add missing `utf8->cork` in `tm_files.scm`
Fix bug [71_37](https://gitee.com/XmacsLabs/mogan/issues/I9BUHT).
* Install target research
* open files from menu
* CI is unreliable here
> [71_37] fix corrupted encoding inside prompt of file failure

- TeXmacs/progs/generic/format-menu.scm
Remove the duplicated separator in the submenu of `Format -> Color`
+ [x] Linux
+ [ ] macOS
+ [ ] Windows
Check the submenu of `Format->Color`.
> [71_39] UI: Remove the duplicated separator in the submenu of Format->Color

- src/Edit/Modify/edit_text.cpp
as title
+ [x] Linux
+ [ ] Windows
+ [ ] macOS
`Insert->Image->Insert image...` of a image with Chinese file name, for example: `微信图片_xxxx.jpg`
The file name of the inserted image should be `微信图片_xxxx.jpg`.
> [64_7] Fix the encoding of the name for the inserted images

- src/Graphics/Gui/widget.hpp
as title
The removal of `virtual` in `inline virtual derived_this ()` leads to a segment fault.
+ [x] Linux
+ [ ] macOS
+ [x] Windows
Without this pull request:
1. Open `Help->Plugins->Binary`
2. Use the Replace widget to replace `python3` with `gs`
3. Close the replace widget
4. Open `Help->Plugins->Maxima` and then there will be a segmentation fault at `src/Edit/Interface/edit_repaint.cpp:430`
With this pull request, it will be fixed.
> [78_2] Add the missing virtual for widget_rep:derived_this

- TeXmacs/progs/convert/images/tmimage.scm
- TeXmacs/progs/texmacs/texmacs/tm-server.scm
`Edit->Copy to->Image` does not work because `(get-preference "texmacs->image:format")` is `"default"`
+ [x] Linux
+ [ ] macOS
+ [x] Windows
Select something in the buffer, and click `Edit->Copy to->Image` and then paste it somewhere else.
> [20_10] Fix Edit->Copy to->Image by setting texmacs->image:format to png

- TeXmacs/progs/source/macro-search.scm
as title
to speed up `search-options` and `search-parameters`
Bench `object xmenu= call ("menu-expand", eval ("'" * menu));` in `tm_window_rep::get_menu_widget`
We can find that in beamer style, in the inserted beamer `tit`, menu-expand time of the focus toolbar could be reduced from 96ms to 55ms after the speed up of `search-options`, and it is reduced from 55ms to 25ms after the speed up of `search-parameters`.
> [79_1] Properly caching to speed up search-options and search-parameters

- src/Plugins/Qt/qt_gui.cpp
as title
+ [x] Linux
+ [ ] macOS
+ [ ] Windows
Steps:
1. Disable autosave
2. Restart Mogan Research
3. Open Help->Welcome, and edit randomly and wait for 100% CPU
Related bug: https://savannah.gnu.org/bugs/?62156
> [7_13] Fix 100% CPU when delay is 0 and delayed_commands.wait is false

- tests/L3/Data/String/wencoding_test.cpp
Added wencoding test, suspected problems with wencoding.
Testing for the function mogan\src\Data\String\wencoding.cpp. Specifically, when testing the guess_wencoding function, it misjudged strings encoded in ISO_8859. When only ascii or utf8 is recognized, the test passes normally. The other two tests, western_to_utf8 and western_to_cork, both failed.
针对mogan\src\Data\String\wencoding.cpp这个功能进行测试。具体来说是在测试guess_wencoding函数的时候，对iso_8859编码的字符串进行了误判。只对ascii或者utf8判别的时候，测试是能正常通过的。另外就是western_to_utf8和western_to_cork两个测试都没能正常通过。
Put it in "mogan\tests\L3\Data\String\wencoding_test.cpp", and then run "xmake build wencoding_test" and "xmake run wencoding_test"
> [14_7] Added wencoding test, suspected problems with wencoding

- src/Plugins/Qt/qt_picture.cpp
`Edit->Copy as->Image` on windows will produce image with black background. Set the fill color to `QColor(255, 255, 255, 255)`, to fix the issue.
Affected:
+ qt_image_renderer_rep
+ picture_renderer
+ make_raster_image
+ `Edit->Copy as->Image`
+ renderer_rep::shadow 
+ Still need to be confirmed
Select something and click `Edit->Copy as->Image` and paste the image somewhere else.
> [64_8] Fill printed raster image with FFFFFFFF

- TeXmacs/fonts/font-database.scm
- src/Graphics/Fonts/font.hpp
- src/Graphics/Fonts/font_database.cpp
- src/Plugins/Freetype/tt_file.cpp
- src/Plugins/Freetype/tt_file.hpp
+ Import the font to $TEXMACS_HOME_PATH/fonts/truetype
- Use the md5 digest as the font file name
- No longer loading fonts from the font local path on macOS/Linux/Windows
+ Collect the font info when loading the font database
+ Fix the bug of tt_fint_font when the font file is using TTF/TTC/OTC as the suffix
TODO: in later pull request: the dialogue to import font should only allow ttf/ttc/otc
`ft_load_face` does not work on windows when the font path contains Chinese characters (eg. `方正小标宋简.ttf`). To avoid Chinese font path name, we use the content md5 digest as the file name when import the font.
The goal of this pull request is to support `方正小标宋简.ttf`, and because of the bug of ft_load_face, we have to re-impl the mechanism of font importing.
+ [x] Linux
+ [ ] macOS
+ [x] Windows
1. …
> [11_31] Import font to $TEXMACS_HOME_PATH/fonts/truetype

- docs/guide/Develop_on_Linux.md
Fedora installation instructions were out of date
- xmake is now available in the main repo
- libgit2 needs to be installed as a dependency
you can test the installation instructions in a docker container via  
docker run --rm -it fedora
> [5_15] update fedora installation instructions

- TeXmacs/plugins/s7/progs/code/s7-lang.scm
- TeXmacs/tests/tm/70_9.tm
- src/Data/Parser/keyword_parser.cpp
- src/Data/Parser/keyword_parser.hpp
- src/Data/Parser/number_parser.cpp
- src/Data/Parser/number_parser.hpp
- src/System/Language/prog_language.cpp
+ number_parser: support `#` prefix
+ keyword_parser: support customizing extra chars
+ improve s7-lang.scm
In S7 Scheme
``` scheme
#b001
#xab1
#o777
#t 
#f
string->number
string?
set!
```
Launch Mogan Research and check `TeXmacs/tests/tm/70_9.tm`
> [70_9] Parser: improve number_parser and keyword_parser for S7 Scheme

- TeXmacs/plugins/s7/progs/code/s7-lang.scm
- src/Data/Parser/keyword_parser.cpp
+ keyword_parser:
- keyword should start with alpha or extra chars
- keyword should be consist of alpha/extra chars/digits
+ Add `+inf.0`, `+inf.0` to S7 Scheme keywords as constant
> [70_9] Improve keyword_parser for +inf.0 and -inf.0

- TeXmacs/plugins/html/progs/convert/html/tmhtml.scm
- TeXmacs/tests/html/2_18.html
- TeXmacs/tests/tm/2_18.tm
+ `hash-map->list` is missing in S7 (it is a routine in GNU Guile, and the behavior in GNU Guile 1.8 and GNU Guile 3.x is not the same)
+ `string-prefix?` is missing in S7 and Mogan
To make `Tools->Create website` works!
Manually convert `2_18.tm` to `2_18.html`
> [2_18] S7: Fix tm->html with ornament

- TeXmacs/plugins/stm/progs/data/stm.scm
- TeXmacs/progs/convert/rewrite/init-rewrite.scm
- TeXmacs/progs/init-research.scm
Move stm related format definition to plugin.
We need to implement the mgs format, which is similar to stm format.
1. Launch Mogan Research
2. Open `Help->Welcome`
3. Save the doc as stm format
> [66_7] Data: stm data format as a plugin

- TeXmacs/plugins/mgs/progs/data/mgs.scm
- TeXmacs/progs/init-research.scm
- src/Data/Tree/tree_traverse.cpp
- src/Data/Tree/tree_traverse.hpp
- src/Scheme/L4/glue_tree.lua
Mogan Scheme is serialized in UTF-8 while TeXmacs Scheme is serialized in cork.
Mogan Scheme format (.mgs) is the frontier of TMU format.
Manually save a document to Mogan Scheme format.
The conversion between TeXmacs scheme and Mogan scheme depends on the conversion between Cork and UTF-8.
> [66_7] Mogan Scheme data format (.mgs)

- src/Data/Convert/Mogan/from_tmu.cpp
TMU is a brand new format, it does not need to be compatible with the legacy TeXmacs versions.
> [66_4] TMU: deprecate compat with old TeXmacs versions

- src/Data/Convert/Mogan/from_tmu.cpp
- src/Data/Convert/Mogan/to_tmu.cpp
Here is the simplest TMU doc containing Hello:
```
<TMU|<tuple|1.0.1|2.1.2>>
<style|generic>
<\body>
Hello
</body>
```
`1.0.1` is the version of TMU.
`2.1.2` is the version of GNU TeXmacs.
> [66_5] TMU: starts with <TMU|<tuple|1.0.1|2.1.2>>

- tests/Plugins/Database/database_basic_function_test.cpp
The tests cover some scenarios to ensure the completions feature works as expected, including:
- Completions for multiple full matches ("abcd": "abcd", "abcd5678")
- Completions for a partial match starting with a specific prefix
> [14_11] Add a unit test for get_completions() in TestDatabaseBasicFunction

- TeXmacs/fonts/virtual/emu-relations.vfn
- TeXmacs/progs/language/std-symbols.scm
- TeXmacs/progs/math/math-kbd.scm
- TeXmacs/progs/texmacs/keyboard/latex-kbd.scm
Add `\varparallel` and `\nvarparallel`.
These symbols are widely used in plane and solid geometry.
Use `\varparallel` and `\nvarparallel` in math mode.
> [14_13] Add varparallel and nvarparallel

- TeXmacs/progs/texmacs/menus/file-menu.scm
- TeXmacs/progs/texmacs/texmacs/tm-files.scm
Temporarily switch to TMU for `File->Save` and `File->Save as`
Let the developers test tmu, and for v1.2.8, we will switch it back.
Try `File->Save` or `File->Save as`.
> [66_9] TMU: switch to tmu for Save and Save as

- TeXmacs/tests/tmu/66_8_escape_0.tmu
- TeXmacs/tests/tmu/66_8_escape_n.tmu
- TeXmacs/tests/tmu/66_8_escape_r.tmu
- TeXmacs/tests/tmu/66_8_escape_t.tmu
- src/Data/Convert/Mogan/from_tmu.cpp
- src/Data/Convert/Mogan/to_tmu.cpp
Deprecate the handling of `\0`.
Simplify the TMU format.
Open `66_8_escape_0.tmu`, insert `a` after `\0`, and save the TMU doc. You will find `\0` will be replaced by `.
After this pull request, `\0` will be replaced by `0`.
> [66_8] TMU: Deprecate \0,\n,\t,\r escaping

- TeXmacs/packages/compute/session.ts
as title
When customizing input/output, we usually customizing generic input/output or cpp input/output.
None.
> [61_11] Set mode to prog in generic input/output instead of input/output

- TeXmacs/plugins/html/progs/convert/html/htmlout.scm
- TeXmacs/plugins/html/progs/convert/html/tmhtml.scm
Change header to HTML5 standard
1. Simplify DOCTYPE Declaration: HTML5 uses a much simpler <!DOCTYPE html> declaration compared to XHTML. This eliminates the need for additional identifiers and URLs.
2. Remove XML Namespaces: HTML5 doesn't require XML namespace declarations (xmlns). These were necessary for XHTML but are redundant in HTML5.
3. Streamline Header Information: HTML5 does not need the XML processing instruction (<?xml version="1.0" encoding="UTF-8"?>) used in XHTML.
4. Improve Compatibility: Transitioning to HTML5 ensures better compatibility with modern web standards and browsers, simplifying maintenance and future development.
> [24_10] Change header to HTML5 standard

- TeXmacs/plugins/html/progs/convert/html/htmlout.scm
- TeXmacs/plugins/html/progs/convert/html/tmhtml.scm
- TeXmacs/tests/24_10.scm
- TeXmacs/tests/24_11.scm
Add encoding & meta tag self-close
TMU:
```
<TMU|<tuple|1.0.2|1.2.8-alpha2>>
<style|<tuple|generic|no-page-numbers>>
<\body>
<doc-data|<doc-title|This is a title>>
</body>
<\initial>
<\collection>
<associate|page-medium|paper>
<associate|page-screen-margin|false>
</collection>
</initial>
```
Previous exported html:
```html
<title>This is a title</title>
<meta content="TeXmacs 2.1.2" name="generator"></meta>
<style type="text/css">
```
Now exported html:
```html
<title>This is a title</title>
<meta content="TeXmacs 2.1.2" name="generator" />
<meta charset="UTF-8" />
<style type="text/css">
```
If you submit the previously exported XHTML standard html to w3c (https://validator.w3.org/), you will find the following error reported:
This error will not occur after the change.
> [24_11] HTML: Add encoding & self-close tags

- TeXmacs/tests/43_2.scm
as title
The `load-buffer` glued scheme routines will result to a side effect on the S7 Scheme engine.
Use `let` to bind the evaluated value first, and then check. In other words, check after the side effect.
```
xmake r 43_2
```
The success count should be 1 instead of 0.
> [43_2] Minor: Fix check count because of execution order

- TeXmacs/plugins/goldfish/goldfish/scheme/boot.scm
- TeXmacs/plugins/goldfish/progs/init-goldfish.scm
- TeXmacs/plugins/goldfish/src/goldfish.cpp
+ Deprecate `--texmacs`
+ Find the load-path for standard library and SRFI by relative path
+ Simplify the command line
+ Do not depend on the environment variable `TEXMACS_PATH`
Build and launch Mogan Research, and then insert the Goldfish session to test
> [61_7] Goldfish: deprecate --texmacs and find the load path via relative path

- TeXmacs/tests/24_14.scm
- TeXmacs/tests/tm/24_14.tm
- src/Plugins/Qt/qt_widget.hpp
Fix crash when exporting tm/tmu docs to HTML with the `-headless` option
When exporting TeXmacs/Mogan documents to html and using the `-headless` option, Mogan will crash for several documents in planet. That's why we added a blacklist in https://github.com/XmacsLabs/planet/pull/37/
```
xmake r 24_14
```
> [24_14] Fix unhandled slots in headless mode

- src/Graphics/Fonts/smart_font.cpp
- xmake/research.lua
as title
Debugging font related issue is painful. We put the curcial logging in the std channel and when `xmake r research`, we enable the `-d` flag to show the logging also in the std logging channel.
> [11_33] Font: put crucial logging in the std channel

- xmake/packages/l/lolly/xmake.lua
- xmake/vars.lua
This reverts commit c5710ef08031c909e3f2f0a9e3a572af1bf91279.
> [75_32] Revert: Upgrade to lolly 1.4.27

- TeXmacs/progs/texmacs/menus/tabpage-menu.scm
Keep tab-title and doc-path of tab pages untranslated.
The tab title and doc path of file `session.tm` are translated into Chinese which is not expected.
> [81_5] Keep tab-title and doc-path of tab pages untranslated

- TeXmacs/progs/education/edu-edit.scm
fix mismatched parameter names
```
;unbound variable forwards? in (if (mc-context? t) (insert-mc-field t forwards?) (former t downwards?))
;    (if (mc-context? t) (insert-mc-field...
;    C:\Users\jingkaimori\Documents\Source\mogan\build\packages\app.mogan\data\progs\education\edu-edit.scm, line 316, position: 0
; (if (mc-context? t) (insert-mc-field t fo... ; t: <tree <mc|<mc-field|false|\<#67...
;                                              downwards?: #t
; ((r (cpp-get-preference which (if s? def ...
; ((with after? (in-inactive-reference?) (w... ; before?: #f
```
In course style, insert multichoice box, then insert item vertically (only possible with shortcuts, i.e. alt+uparrow on windows)
> [61_16] Education: fix typo in edu-edit

- TeXmacs/plugins/gnuplot/goldfish/tm-gnuplot.scm
- TeXmacs/plugins/gnuplot/progs/init-gnuplot.scm
- TeXmacs/plugins/goldfish/goldfish/texmacs/protocol.scm
Reimplement the Gnuplot plugin in Goldfish Scheme.
1. Some people have trouble installing Python on Windows, they are complaining that they failed to get the gnuplot plugin work on Windows
2. Less deps, because goldfish is built-in, we only need to install gnuplot
Launch the gnuplot session.
> [61_5] Gnuplot: initial rework

- TeXmacs/tests/tm/80_1.tm
- src/Graphics/Fonts/smart_font.cpp
Fix math bracket fonts in Chinese docs.
In Chinese documents, some math brackets display improperly.
Open `TeXmacs/tests/tm/80_1.tm` file in mogan.
Before (wrong):
After (right):
> [80_1] Fix math bracket fonts in Chinese docs

- TeXmacs/tests/19_8.scm
- TeXmacs/tests/tmu/19_8_french.tmu
- src/System/Language/dictionary.cpp
as title
The encoding change of the scheme file  breaks the translation mechanism.
```
xmake r 19_8
```
or open 19_8_french.tmu
> [19_8] Language dic: fix for the UTF-8 encoding change

- src/Data/Tree/tree_analyze.cpp
- src/Edit/Modify/edit_delete.cpp
- src/System/Language/impl_language.hpp
- src/System/Language/language.cpp
- src/System/Language/language.hpp
- src/System/Language/math_language.cpp
- src/System/Language/prog_language.cpp
- src/System/Language/scheme_language.cpp
- src/System/Language/text_language.cpp
- src/System/Language/verb_language.cpp
- src/Typeset/Concat/concat_text.cpp
- src/Typeset/Concat/concater.cpp
This reverts commit 361f1c14f74895ade3c59f4c1e9c1ece3596121f.
inverse path get from argument is the same as ones obtained by `obtain_ip`, thus change is unnecessary.
> [70_12] Revert: Language: add current ip for advance

- src/Edit/Editor/edit_main.cpp
When some snippet is printed, this snippet is inserted into the_et first, then typesetter is invoked with proper reverse path.
Because a empty path is passed to typesetter, several error messages about improper path is printed when printing snippets. If at least two blocks of code is selected and exported, mogan will crash.
> [20_12] fix corrupted ip(inversed path) when tree is exported to image

- TeXmacs/tests/24_15.scm
Refine test for docx.scm
The docx export logic has been changed, so the associated tests need to be altered as well.
xmake r 24_15
> [24_15] Refine test for docx.scm

- TeXmacs/plugins/code/progs/code/default-ast-lang.scm
- TeXmacs/plugins/goldfish/progs/code/goldfish-ast-lang.scm
- TeXmacs/plugins/goldfish/progs/code/goldfish-lang.scm
- src/Plugins/Treesitter/lang_parser.cpp
- src/Plugins/Treesitter/lang_parser.hpp
- src/System/Language/ast_language.cpp
- src/System/Language/prog_language.cpp
Goldfish Scheme is a scheme dialect.
We introduce:
```
(tm-define (parser-feature lan key)
(:require (and (== lan "goldfish") (== key "id")))
`(,(string->symbol key)
"scheme"))
```
To make goldfish dependes on the `scheme` tree-sitter parser. The only difference between the scheme language and the goldfish language lies on the keywords.
For customized language.
Check the ast option, and insert a Goldfish session.
> [70_13] Allow set lang_id for customized language

- TeXmacs/tests/24_19.scm
- src/Data/String/converter.cpp
Avoid converting Chinese to hexadecimal when exporting html.
When exported tm, tmu format to html before, Chinese was displayed in hexadecimal. After modification, Chinese can be displayed normally in html.
Text in tmu:
Text in html:
Open html in browser:
> [24_19] Avoid converting CJK to hexadecimal when exporting html

- TeXmacs/progs/text/text-menu.scm
- TeXmacs/tests/43_3.scm
- TeXmacs/tests/71_41.scm
1. Use `        <=` as an indicator of the current menu
2. If the section items is bigger than 42, only reserve the full items in the current focus, for others, only reserve chapter and part
We have a doc with too many section items.
Manually test it.
> [71_41] UI: Improve the focus-section-menu

- TeXmacs/plugins/docx/progs/data/docx.scm
Set default export to docx to use MathML instead of image.
At present, the function of using MathML for export has been relatively perfect.
> [24_21] Set default export to docx to use MathML instead of image

- src/Plugins/Treesitter/lang_parser.cpp
- src/Plugins/Treesitter/lang_parser.hpp
- src/System/Language/ast_language.cpp
1. `get_root_node` relies on the result of `get_child_env` to determine whether it is a code node.
2. Fixed `get_code_from_root` and `get_data_from_root` to support string nodes.
3. Fixed a minor bug in `add_single_token`.
Incorrect code root node can lead to performance degradation, rendering errors, and PDF export failures.
Use Syntax Highlight
> [70_14] Fix the retrieval and processing of the root node in lang_parser

- src/Plugins/Treesitter/lang_parser.cpp
- src/Plugins/Treesitter/lang_parser.hpp
1. With node may cause wrong root code
2. If a prog node is not encountered, the entire document will be rendered, leading to performance issues.
1. A with node has more than one string child node, and only the last child node is the one that is actually rendered as a string node.
2. When a prog node is not encountered, it uses its own string node for rendering.
> [70_16] Fix with node cause wrong root code and no prog root fallback

- devel/78.tmu
- src/Plugins/Tex/fromtex.cpp
- src/Typeset/Boxes/Basic/boxes.cpp
Fix warnings
`src\Typeset\Boxes\Basic\boxes.cpp(898): warning C4551: function call missing argument list`
`src\Plugins\Tex\fromtex.cpp(2635): warning C4129: '{': unrecognized character escape sequence`
import latex file test.tex: `123{123}\{123\}\cases{123}` shows that `"\{"` in fromtex.cpp should be `"{"` instead of `"\\{"`.
> [78_8] Fix warning: remove unused

- TeXmacs/plugins/docx/progs/data/docx.scm
- docs/guide/plugin_data_docx.md
- docs/zh/guide/plugin_data_docx.md
As title
To call the no-install version of pandoc must get the pandoc path in the environment variable PATH, which is not recommended.
Added a debug information to inform user which pandoc is being used.
> [24_22] Add documentation to remind users to use the installed version of pandoc

- src/Plugins/Treesitter/lang_parser.cpp
1. An incorrect `hash (tree)` can lead to an inability to recompile.
2. The first line being empty can cause rendering errors.
1. An additional item has been added to the hash_code.
2. Change `change_line_high > 0` to `change_line_high >= 0`.
> [70_18] Fix wrong hash code and empty first line

- TeXmacs/packages/environment/env-program.ts
- TeXmacs/plugins/code/progs/prog/prog-kbd.scm
- TeXmacs/plugins/python/packages/code/python.ts
- TeXmacs/progs/text/text-menu.scm
- TeXmacs/tests/tmu/61_2_python_code.tmu
- src/Typeset/Concat/concat_text.cpp
One must add the python.ts style file to use `python` and `python-code`.
To make python syntax highlight pluggable and stable.
> [61_2] Python: move the python and python-code tag to python.ts

- src/Plugins/Treesitter/lang_parser.cpp
- src/Plugins/Treesitter/lang_parser.hpp
The inaccurate line_hash sometimes prevents the code from being re-rendered correctly. The old line_hash for four spaces and three spaces is the same.
> [70_18] Fix the inaccurate method of obtaining line_hash

- devel/80_4.tmu
- src/Graphics/Fonts/font.cpp
- src/Graphics/Fonts/font.hpp
- src/Plugins/Freetype/tt_face.cpp
- src/Plugins/Freetype/tt_face.hpp
- src/Plugins/Freetype/tt_tools.hpp
- src/Plugins/Freetype/unicode_font.cpp
- src/Typeset/Boxes/Composite/script_boxes.cpp
Improving the Typesetting of Limit Boxes.
For some OpenType fonts, the heights of the upper and lower limits in the limit box environment are not suitable.
Open `devel/80_4.tmu`.
Before (Anasa Math font), the upper limit is too high:
After:
> [80_4] Improving the Typesetting of Limit Boxes

- devel/80_5.tmu
- src/Graphics/Fonts/font.cpp
- src/Graphics/Fonts/font.hpp
- src/Plugins/Freetype/unicode_font.cpp
- src/Typeset/Boxes/Composite/math_boxes.cpp
- src/Typeset/Boxes/construct.hpp
- src/Typeset/Concat/concat_math.cpp
Improving Fraction Box Typesetting.
For some OpenType fonts, the heights of the numerator and denominator in the fraction box environment are not suitable.
Open `devel/80_5.tmu`.
Before (Anasa Math font):
After:
> [80_5] Improving Fraction Box Typesetting

- devel/80_3.tmu
- src/Plugins/Freetype/tt_tools.cpp
- src/Plugins/Freetype/tt_tools.hpp
- src/Plugins/Freetype/unicode_font.cpp
- src/Plugins/Freetype/unicode_font.hpp
We have utilized the italic correction table and kerning table in OpenType to optimize the typesetting of superscripts and subscripts.
However, it is important to note that this implementation is non-standard.
The italic correction table is used to improve the typesetting on the right side of glyphs. For general characters, the right subscript uses the default position, while the right superscript needs to be shifted to the right by this correction. For symbols like integral signs, the official documentation suggests that both the right superscript and right subscript should be moved by half the offset, while some documents recommend that the superscript remain stationary and the subscript be moved by the full offset. For aesthetic reasons, we have adopted a compromise solution here, …
> [80_3] Enhance sup/subscript kerning via OpenType math table

- TeXmacs/tests/tmu/80_9.tmu
- src/Graphics/Fonts/smart_font.cpp
Render the single character in math mode as italic math unicode.
For Latin Modern Math, it is using the pool italic fallback font and it is very ugly.
Open 80_9.tmu
Before:
Now:
> [80_9] Font: render as italic for math font family ending with Math

- TeXmacs/plugins/goldfish/goldfish/goldfish/repl.scm
- TeXmacs/plugins/goldfish/goldfish/liii/base.scm
- TeXmacs/plugins/goldfish/goldfish/liii/base64.scm
- TeXmacs/plugins/goldfish/goldfish/liii/bitwise.scm
- TeXmacs/plugins/goldfish/goldfish/liii/list.scm
- TeXmacs/plugins/goldfish/goldfish/liii/os.scm
- TeXmacs/plugins/goldfish/goldfish/liii/string.scm
- TeXmacs/plugins/goldfish/goldfish/liii/vector.scm
- TeXmacs/plugins/goldfish/goldfish/scheme/base.scm
- TeXmacs/plugins/goldfish/goldfish/srfi/srfi-133.scm
- TeXmacs/plugins/goldfish/goldfish/srfi/srfi-151.scm
- TeXmacs/plugins/goldfish/src/goldfish.hpp
- TeXmacs/tests/71_41.scm
Bump goldfish scheme into 17.10.8.
> [61_7] bump to Goldfish Scheme v17.10.8

- TeXmacs/progs/generic/generic-kbd.scm
Add `std =` as a keybinding for zoom-in
`C-=` for zoom in is nice than pressing `C-S-=`.
+ [x] Linux (KDE)
+ [ ] macOS
+ [ ] Windows
> [59_23] Keyboard: Add std = as a keybinding for zoom-in

- src/Mogan/Research/research.cpp
By default logging into `$TEXMACS_HOME_PATH/system/YYYYmmddHH.log`.
Use `-d` or `-debug` to disable logging and show it on the console on macOS and Linux.
For debugging perpose, especially on Windows.
> [7_17] Enable logging for non-debug mode

- .github/workflows/cd_research_on_fedora.yml
> [73_24] CD for Fedora

- src/Edit/Interface/edit_interface.cpp
Add check before adding new values to `edit_interface_rep::copy_always` in function `edit_interface_rep::apply_changes()`.
New rectangle will be added to `copy_always` if `copy_always` is empty/nil or the first item of `copy_always` is not equal to newly added value.
Since `apply_changes()` will be called when the window receives any event, `copy_always` will become very large and cause stack overflow when it's cleared.
The `copy_always` is a linked list and when it's cleared, the destructor is called from head to tail recursively, causing stack overflow.
That's the potential risk: I can only test it on Windows with few scenarios, I don't know the result in Linux, Mac.
already run `xmake run --yes -vD --group=tests` and `xmake run --yes -vD --group=integration_tests`
The investigations …
> [20_13] Do not add duplicated values to copy_always to avoid stack overflow

- docs/zh/guide/SourceCode.md
docs: 修复源码链接地址
- 修正 GitCode 链接地址中的拼写错误
- 将 "https://gitcode.org/XmacsLabs/mogan" 修改为 "https://gitcode.com/XmacsLabs/mogan"
> [5_32] docs: 修复源码链接地址

- TeXmacs/progs/graphics/graphics-markup.scm
- TeXmacs/tests/23_27.scm
Fix 2 little bugs.
1. Can not draw the correct semicircle in current environment.
2. There will be "division by zero" exception in console when you're choosing the third point and move mouse to center point (the first point).
When drawing an arc, we first select the circle center `c`, then the start point `p` and end point `x` on the arc.
It will use these points to calculate a third point `m` on arc, and use `p`, `m`, `x` to draw the arc.
By default it's counterclockwise though it's called "Std-arc".
When we want to draw a semicircle, the angle between `vec-c-p` and `vec-c-q` is 180.
In the previous code, it uses `vec-c-p` as the third point `m` incorrectly.
We should still consider it's clockwise or counterclockwise here and then add the correct vector to the center point as the third …
> [23_27] Fix bugs when drawing semicircle
